load("//ts:rules.bzl", "eslint_test", "jest_test", "ts_lint", "ts_project")

package(default_visibility = ["//:__subpackages__"])

exports_files(
    ["rule.ts"],
    visibility = ["//:__subpackages__"],
)
