load("//ts:rules.bzl", "ts_project")

package(default_visibility = ["//ts/pulumi/me:__pkg__"])

ts_project(
    name = "zemn",
    deps = [
        "//ts/pulumi/me/zemn/factorio",
        "@npm//@pulumi/aws",
        "@npm//@pulumi/pulumi",
    ],
)
