load("@aspect_rules_js//js:defs.bzl", "js_test")
load("@npm//:renovate/package_json.bzl", "bin")
load("//bzl:rules.bzl", "bazel_lint")
load("//js:rules.bzl", "js_library")
load("//md:rules.bzl", "md_files")
load("//yml:test.bzl", "yaml_lint_test")

exports_files(["renovate-global.json"])

bin.renovate_config_validator_test(
    name = "validate_renovate_config_test",
    args = [
        "$(location renovate-global.json)",
        "--strict",
    ],
    data = ["renovate-global.json"],
)

yaml_lint_test(
    name = "validation",
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

md_files(
    name = "github",
    srcs = ["AGENTS.md"],
    visibility = ["//:__subpackages__"],
)

js_test(
    name = "renovate_pnpm_test",
    size = "small",
    data = [
        ":renovate_pnpm_test_mjs",
        "//:package_json",
        "@pnpm",
    ],
    entry_point = "renovate_pnpm_test.mjs",
    env = {
        "PACKAGE_JSON": "$(rlocationpath //:package_json)",
        "PNPM_BIN": "$(rlocationpath @pnpm//:pnpm)",
    },
)

js_library(
    name = "renovate_pnpm_test_mjs",
    srcs = ["renovate_pnpm_test.mjs"],
    deps = [
        "//:node_modules/@bazel/runfiles",
        "//:node_modules/renovate",
    ],
)
