openapi: 3.0.4
info:
  title: zemn.me API
  version: 0.0.0

servers:
  - url: https://api.zemn.me
    description: Production
  - url: http://api.staging.zemn.me
    description: Staging

components:
  securitySchemes:
    googleOIDC:
      type: openIdConnect
      openIdConnectUrl: "https://accounts.google.com/.well-known/openid-configuration"
  schemas:
    PhoneNumber:
      description: A single E.164 phone number.
      example: "+447823423420"
      type: string
      pattern: ^\+[1-9]\d{1,14}$

    EntryCode:
      description: A 5 digit PIN-like entry code that may be used by a user.
      example: "56734"
      type: string
      pattern: ^\d{5}$

    CallboxSettings:
      description: >
        Settings object used by the callbox.
      type: object
      required:
        - authorizers
        - fallbackPhone
        - entryCodes
      properties:

        authorizers:
          description: >
            A list of E.164 phone numbers. Authorizers are phone numbers that
            can be requested by the visitor — the callbox will then connect the
            authorizer who may press 9 at any time to approve visitor entry.
          type: array
          items:
            $ref: "#/components/schemas/PhoneNumber"

        fallbackPhone:
          description: >
            This number is called when the visitor does not request anything
            specific, or if the visitor fails to get in via some other method.

            It is a single E.164 phone number.

          $ref: "#/components/schemas/PhoneNumber"

        entryCodes:
          description: >
            A set of PIN-like numbers that may be used for immediate entry.
          type: array
          items:
            $ref: "#/components/schemas/EntryCode"


    Error:
      description: >
        Sent if an error occurs.
      type: object
      required:
        - cause
      properties:
        cause:
          type: string
          example: Too many concurrent requests.
    GetPhoneNumberResponse:
      description: >
        Object representing the current callbox phone number.
      type: object
      required:
        - phoneNumber
      properties:
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumber"

paths:
  /phone/init:
    get:
      summary: Entry point for twilio callbox phone number.
      responses:
        "200":
          description: It worked ig.
          content:
            application/xml:
              schema:
                type: string
  /phone/handleEntry:
    get:
      parameters:
        - name: Digits
          in: query
          description: digits entered by user.
          required: false
          schema:
            type: string
      summary: Handles entering an authorizer for the callbox phone number.
      responses:
        "200":
          description: It worked ig.
          content:
            application/xml:
              schema:
                type: string


  /callbox/settings:
    post:
      description: >
        Return the current callbox settings.
      security:
        - googleOIDC: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CallboxSettings"
      responses:
        "200":
          description: >
            Settings as synced with the backend.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallboxSettings'
        "500":
            description: Error.
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
    get:
      description: >
        Returns the current settings for the callbox.
      security:
        - googleOIDC: []
      responses:
        "500":
          description: >
            Something went wrong.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "200":
          description: >
            Returns a list of phone numbers representing users
            who are authorised to approve entry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallboxSettings'
  /phone/number:
    get:
      summary: Returns the current phone number for the callbox.
      security:
        - googleOIDC: []
      responses:
        "200":
          description: It worked!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPhoneNumberResponse'
