load("//bzl:rules.bzl", "bazel_lint")
load("//js:rules.bzl", "js_library")
load("//md:rules.bzl", "md_files")
load("//ts:rules.bzl", "jest_test", "ts_project")

package(default_visibility = ["//:__subpackages__"])

js_library(
    name = "public",
    srcs = [
        "public/404.html",
        "public/index.html",
        "public/photos/back.jpg",
        "public/photos/cover.jpg",
        "public/photos/inside-left.jpg",
        "public/photos/inside-right.jpg",
        "public/style.css",
    ],
)

ts_project(
    name = "bowerybugle.nyc",
    srcs = ["index.ts"],
    data = [":public"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:node_modules/@pulumi/aws",
        "//:node_modules/@pulumi/pulumi",
        "//:node_modules/@types/node",
        "//ts/pulumi/lib/website",
    ],
)

jest_test(
    name = "infra_test",
    srcs = ["infra_test.js"],
    visibility = ["//:__subpackages__"],
    deps = [":bowerybugle.nyc_tests"],
)

filegroup(
    name = "all_ts_srcs",
    srcs = [
        "index.ts",
        "infra_test.ts",
        "site_test.ts",
    ],
    visibility = ["//:__subpackages__"],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

md_files(
    name = "docs",
    srcs = ["README.md"],
    visibility = ["//:__subpackages__"],
)

jest_test(
    name = "site_test",
    srcs = ["site_test.js"],
    data = [":public"],
    jsdom = True,
    deps = [":bowerybugle.nyc_tests"],
)

ts_project(
    name = "bowerybugle.nyc_tests",
    srcs = [
        "infra_test.ts",
        "site_test.ts",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":bowerybugle.nyc",
        "//:node_modules/@jest/globals",
        "//:node_modules/@pulumi/pulumi",
        "//:node_modules/@types/node",
    ],
)
