load("//bzl:rules.bzl", "bazel_lint")
load("//md:rules.bzl", "md_files")
load("//ts:rules.bzl", "jest_test", "ts_project")

# gazelle:resolve typescript typescript #root/project/nyc/bowerybugle/cmd/api/BoweryBugleImage.js //project/nyc/bowerybugle/cmd/api:oci_image

package(default_visibility = ["//:__subpackages__"])

alias(
    name = "public",
    actual = "//ts/pulumi/bowerybugle.nyc/public:public",
)

ts_project(
    name = "bowerybugle.nyc",
    srcs = [
        "backend.ts",
        "index.ts",
    ],
    data = [":public"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:node_modules/@pulumi/aws",
        "//:node_modules/@pulumi/pulumi",
        "//:node_modules/@types/node",
        "//project/nyc/bowerybugle/cmd/api:oci_image",
        "//ts/pulumi/lib",
        "//ts/pulumi/lib/website",
    ],
)

jest_test(
    name = "infra_test",
    srcs = ["infra_test.js"],
    visibility = ["//:__subpackages__"],
    deps = [":bowerybugle.nyc_tests"],
)

filegroup(
    name = "all_ts_srcs",
    srcs = [
        "archive_test.ts",
        "backend.ts",
        "index.ts",
        "infra_test.ts",
        "site_test.ts",
    ],
    visibility = ["//:__subpackages__"],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

md_files(
    name = "docs",
    srcs = ["README.md"],
    visibility = ["//:__subpackages__"],
)

jest_test(
    name = "site_test",
    srcs = ["site_test.js"],
    data = [":public"],
    jsdom = True,
    deps = [":bowerybugle.nyc_tests"],
)

ts_project(
    name = "bowerybugle.nyc_tests",
    srcs = [
        "archive_test.ts",
        "infra_test.ts",
        "site_test.ts",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":bowerybugle.nyc",
        "//:node_modules/@jest/globals",
        "//:node_modules/@pulumi/pulumi",
        "//:node_modules/@types/node",
    ],
)

jest_test(
    name = "archive_test",
    srcs = ["archive_test.js"],
    data = [":public"],
    jsdom = True,
    deps = [":bowerybugle.nyc_tests"],
)
