load("//bzl:rules.bzl", "bazel_lint")
load("//js/npm:rules.bzl", "npm_pkg")
load("//md:rules.bzl", "md_files")
load("//ts:rules.bzl", "ts_project")

package(default_visibility = [
    ":__subpackages__",
    "//ci:__subpackages__",
])

DEPS = [
    "//:node_modules/cross-spawn",
    "//:node_modules/@types/cross-spawn",
    "//:node_modules/@types/node",
]

ts_project(
    name = "do-sync",
    srcs = glob(["**/*.ts"]),
    deps = DEPS,
)

npm_pkg(
    name = "npm_pkg",
    srcs = [":do-sync"],
    entry_point = "index.ts",
    files = ["LICENSE"],
    major_version = "version/MAJOR",
    minor_version = "version/MINOR",
    patch_version = "version/PATCH",
    pkg_json_base = "package.template.json",
    readme = "README.md",
    release_lock = ".release.lock",
    test_version_on_main = True,
    tgz = "npm_package",
    visibility = [
        "//ci:__subpackages__",
        "//ts/pulumi:__subpackages__",
    ],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

md_files(
    name = "ts_do_sync",
    srcs = ["README.md"],
    visibility = ["//:__subpackages__"],
)
