package(default_visibility = ["//visibility:public"])

load("//ts:rules.bzl", "ts_config")

ts_config(
    name = "node",
    src = "node.tsconfig.json",
    deps = ["//:tsconfig"],
)

ts_config(
    name = "jsx",
    src = "jsx.tsconfig.json",
    deps = ["//:tsconfig"],
)
