package(default_visibility = ["//visibility:public"])

load(":platform.bzl", "declare_config_settings")

declare_config_settings()

package_group(
    name = "function_transition_whitelist",
    packages = [
        "//...",
    ],
)

