load("//ts:rules.bzl", "ts_project")

ts_project(
    name = "SliderCheckbox",
    srcs = glob([
        "*.ts",
        "*.tsx",
        "*.css",
    ]),
    visibility = ["//project/zemn.me:__subpackages__"],
    deps = [
        "@npm//@types/react",
        "@npm//react",
    ],
)
