load("//bzl:rules.bzl", "bazel_lint")
load("//py:rules.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "doom",
    srcs = [
        "textures.py",
        "wad.py",
    ],
    visibility = ["//:__subpackages__"],
)

py_binary(
    name = "doom_bin",
    srcs = ["__main__.py"],
    main = "__main__.py",
    visibility = ["//:__subpackages__"],
    deps = [":doom"],
)

py_test(
    name = "doom_test",
    srcs = ["__test__.py"],
    main = "__test__.py",
    deps = [":doom"],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)
