load("//ts:rules.bzl", "ts_project")
load("//ts/css/module:rules.bzl", "ts_css_module")

#ts_project(
#    name = "example_ts",
#)

ts_css_module(
    name = "css_files",
    srcs = [ "something.module.css" ]
)