load("//ts:rules.bzl", "ts_project")
load("//:rules.bzl", "ts_config")
load("//ts/pulumi:rules.bzl", "pulumi")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    deps = ["//:tsconfig"],
)

