load("//ts:rules.bzl", "jest_test", "ts_project")

package(default_visibility = ["//:__subpackages__"])

ts_project(
    name = "config_node",
    srcs = ["jest.node.config.ts"],
)

ts_project(
    name = "config_browser",
    srcs = ["jest.browser.config.ts"],
)
