workspace(name = "examples")

load(":examples_repositories.bzl", "repositories")

repositories()

load(":examples_deps.bzl", "deps")

deps()

load(":examples_extra_deps.bzl", "extra_deps")

extra_deps()
