load("//bzl:rules.bzl", "bazel_lint")
load("//ts:rules.bzl", "jest_test", "ts_project")

ts_project(
    name = "doom",
    srcs = [
        "level.ts",
        "mesh.ts",
        "walk.ts",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:node_modules/@types/node",
        "//ts/3d",
        "//ts/math",
    ],
)

filegroup(
    name = "all_ts_srcs",
    srcs = [
        "level.ts",
        "mesh.ts",
        "walk.ts",
        "walk_test.ts",
    ],
    visibility = ["//:__subpackages__"],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

ts_project(
    name = "doom_tests",
    srcs = ["walk_test.ts"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":doom",
        "//:node_modules/@jest/globals",
        "//:node_modules/@types/node",
        "//ts/math",
    ],
)

jest_test(
    name = "tests",
    srcs = ["walk_test.js"],
    visibility = ["//:__subpackages__"],
    deps = [":doom_tests"],
)
