"Shows how you might create a macro for the autogenerated Jest rule"

load("@npm//jest-cli:index.bzl", "jest", _jest_test = "jest_test")

def jest_test(name, srcs, data = [], deps = [], jest_config = "//:jest.ts.config.js", link_workspace_root = True, **kwargs):
    "A macro around the autogenerated jest_test rule"
    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
        "--forceExit",
    ]
    templated_args.extend(["--config", "$(rootpath %s)" % jest_config])

    # Bazel already handles timeouts.
    templated_args.extend(["--testTimeout", str(1000 * 60 * 5)])
    for src in srcs:
        templated_args.extend(["--runTestsByPath", "$(rootpath %s)" % src])

    data = [jest_config] + data + srcs + deps + ["//js/jest:jest_reporter"]

    _jest_test(
        name = name,
        data = data,
        templated_args = templated_args,
        link_workspace_root = link_workspace_root,
        **kwargs
    )

    # This rule is used specifically to update snapshots via `bazel run`
    jest(
        name = "%s.update" % name,
        data = data,
        templated_args = templated_args + ["-u"],
        link_workspace_root = link_workspace_root,
        **kwargs
    )
