load("//bzl:rules.bzl", "bazel_lint")
load("//js:rules.bzl", "js_library")

js_library(
    name = "archive_js",
    srcs = ["archive.js"],
    deps = [],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

js_library(
    name = "public",
    srcs = [
        "404.html",
        "index.html",
        "manage.html",
        "style.css",
    ],
    visibility = ["//ts/pulumi/bowerybugle.nyc:__subpackages__"],
    deps = [":archive_js"],
)
