load("//bzl:rules.bzl", "bazel_lint")
load("//ts:rules.bzl", "jest_test", "ts_project")

ts_project(
    name = "examples",
    srcs = [
        "basic.ts",
        "react.tsx",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:node_modules/@types/node",
        "//:node_modules/@types/react",
        "//:node_modules/react",
        "//ts/result",
    ],
)

filegroup(
    name = "all_ts_srcs",
    srcs = [
        "basic.ts",
        "examples_test.ts",
        "react.tsx",
    ],
    visibility = ["//:__subpackages__"],
)

ts_project(
    name = "examples_tests",
    srcs = ["examples_test.ts"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":examples",
        "//:node_modules/@jest/globals",
        "//:node_modules/@types/node",
        "//ts/result",
    ],
)

filegroup(
    name = "readme_examples",
    srcs = [
        "basic.ts",
        "react.tsx",
    ],
    visibility = ["//ts/result:__pkg__"],
)

jest_test(
    name = "tests",
    srcs = ["examples_test.js"],
    visibility = ["//:__subpackages__"],
    deps = [":examples_tests"],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)
