package(default_visibility = [ "//visibility:public" ])
load("@npm//@bazel/typescript:index.bzl", "ts_config")

ts_config(
    name = "node",
    src = "node.tsconfig.json",
    deps = [ "//:tsconfig" ]
)