load("@io_bazel_rules_go//go:def.bzl", "go_test")
load("@rules_itest//private:itest.bzl", "service_test")
load("//bzl:rules.bzl", "bazel_lint")
load("//bzl/go:oapi_codegen.bzl", "go_oapi_codegen")
load("//go:rules.bzl", "go_library")

go_oapi_codegen(
    name = "server_gen",
    out = "api.gen.go",
    generate = [
        "chi-server",
        "models",
        "strict-server",
        "spec",
    ],
    package = "server",
    source = "//project/nyc/bowerybugle/api:spec.yaml",
)

go_library(
    name = "server",
    srcs = [
        "api.gen.go",
        "aws.go",
        "protocol_http.go",
        "server.go",
        "totp.go",
    ],
    importpath = "github.com/zemn-me/monorepo/project/nyc/bowerybugle/server",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_feature_dynamodb_attributevalue//:attributevalue",
        "@com_github_aws_aws_sdk_go_v2_service_dynamodb//:dynamodb",
        "@com_github_aws_aws_sdk_go_v2_service_dynamodb//types",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_aws_aws_sdk_go_v2_service_sesv2//:sesv2",
        "@com_github_aws_aws_sdk_go_v2_service_sesv2//types",
        "@com_github_getkin_kin_openapi//openapi3",  # keep: generated spec
        "@com_github_getkin_kin_openapi//openapi3filter",
        "@com_github_go_chi_chi_v5//:chi",
        "@com_github_oapi_codegen_nethttp_middleware//:nethttp-middleware",
        "@com_github_oapi_codegen_runtime//:runtime",  # keep: generated router
    ],
)

go_test(
    name = "server_test_bin",
    srcs = [
        "aws_test.go",
        "browser_test.go",
        "protocol_http_test.go",
        "server_test.go",
        "totp_test.go",
    ],
    data = ["//project/nyc/bowerybugle:build"],
    embed = [":server"],
    tags = ["manual"],
    deps = [
        "//go/seleniumutil",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_credentials//:credentials",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_getkin_kin_openapi//openapi3filter",
        "@com_github_getkin_kin_openapi//routers",
        "@com_github_getkin_kin_openapi//routers/gorillamux",
        "@com_github_tebeka_selenium//:selenium",
        "@io_bazel_rules_go//go/runfiles",
    ],
)

bazel_lint(
    name = "bazel_lint",
    srcs = ["BUILD.bazel"],
)

service_test(
    name = "server_test",
    services = ["//project/nyc/bowerybugle:renderer_test_service"],
    test = ":server_test_bin",
)
