"""Rules for generating responsive image srcsets for Next.js."""

load("//image:transcode.bzl", "transcode_img")
load("//ts:rules.bzl", "ts_project")
load("//ts/next.js:public_assets.bzl", "hashed_public_assets")

def _ts_string(value):
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

def _srcset_module_impl(ctx):
    if len(ctx.attr.widths) != len(ctx.attr.jpeg_export_names):
        fail("widths and jpeg_export_names must have the same length")
    if len(ctx.attr.widths) != len(ctx.attr.webp_export_names):
        fail("widths and webp_export_names must have the same length")

    default_jpeg_export_name = ""
    for i, width in enumerate(ctx.attr.widths):
        if width == ctx.attr.default_width:
            default_jpeg_export_name = ctx.attr.jpeg_export_names[i]
            break

    if not default_jpeg_export_name:
        fail("default_width must be one of widths")

    default_jpeg_average_color_export_name = default_jpeg_export_name + "AverageColor"
    imports = ", ".join(
        ctx.attr.jpeg_export_names +
        [default_jpeg_average_color_export_name] +
        ctx.attr.webp_export_names,
    )
    lines = [
        "// Generated by //ts/next.js:image_srcset.bzl",
        "",
        "import { %s } from './%s.js';" % (imports, ctx.attr.sources_module),
        "",
        "export interface ImageSrcsetSource {",
        "\treadonly src: string;",
        "\treadonly width: number;",
        "}",
        "",
        "export interface PictureSourceProps {",
        "\treadonly srcSet: string;",
        "\treadonly sizes: string;",
        "\treadonly type: string;",
        "}",
        "",
        "function toSrcSet(sources: readonly ImageSrcsetSource[]) {",
        "\treturn sources",
        "\t\t.map(source => `${source.src} ${source.width}w`)",
        "\t\t.join(', ');",
        "}",
        "",
        "export const sources = [",
    ]

    for i, width in enumerate(ctx.attr.widths):
        lines.append(
            "\t{ src: %s, width: %d }," % (ctx.attr.jpeg_export_names[i], width),
        )

    lines.extend([
        "] as const satisfies readonly ImageSrcsetSource[];",
        "export const jpegSources = sources;",
        "",
        "export const webpSources = [",
    ])

    for i, width in enumerate(ctx.attr.widths):
        lines.append(
            "\t{ src: %s, width: %d }," % (ctx.attr.webp_export_names[i], width),
        )

    lines.extend([
        "] as const satisfies readonly ImageSrcsetSource[];",
        "",
        "export const src = %s;" % default_jpeg_export_name,
        "export const averageColor = %s;" % default_jpeg_average_color_export_name,
        "export const srcSet = toSrcSet(jpegSources);",
        "export const jpegSrcSet = srcSet;",
        "export const webpSrcSet = toSrcSet(webpSources);",
        "export const sizes = %s;" % _ts_string(ctx.attr.sizes),
        "export const imageProps = { src, srcSet, sizes } as const;",
        "export const pictureSources = [",
        "\t{ srcSet: webpSrcSet, sizes, type: 'image/webp' },",
        "] as const satisfies readonly PictureSourceProps[];",
        "",
    ])

    ctx.actions.write(
        output = ctx.outputs.out,
        content = "\n".join(lines),
    )

    return [DefaultInfo(files = depset([ctx.outputs.out]))]

_srcset_module = rule(
    implementation = _srcset_module_impl,
    attrs = {
        "default_width": attr.int(mandatory = True),
        "out": attr.output(mandatory = True),
        "jpeg_export_names": attr.string_list(mandatory = True),
        "sizes": attr.string(mandatory = True),
        "sources_module": attr.string(mandatory = True),
        "webp_export_names": attr.string_list(mandatory = True),
        "widths": attr.int_list(mandatory = True),
    },
)

def _variant_export_name(format_name, width):
    return "%s%d" % (format_name, width)

def responsive_image_srcset(
        name,
        src,
        widths,
        sizes,
        heights = None,
        jpeg_quality = 85,
        webp_quality = 82,
        fit = "contain",
        crop_scale = None,
        public_dir = "sha256",
        default_width = None,
        visibility = None):
    """Generate responsive WebP/JPEG variants and a TypeScript srcset module.

    Args:
        name: Public TypeScript target name. Also used as the generated module
            basename, so `name = "hero"` produces `hero.ts`.
        src: Source image label.
        widths: Positive integer output widths in CSS pixels.
        sizes: HTML `sizes` attribute value to export.
        heights: Optional positive integer output heights. When provided, this
            must have one entry per width.
        jpeg_quality: JPEG quality from 1 to 100.
        webp_quality: WebP quality from 1 to 100.
        fit: Resize fit mode passed to `transcode_img`: `contain` or `cover`.
        crop_scale: Optional inward crop factor for `cover` fit.
        public_dir: Next public directory for content-addressed assets.
        default_width: Width to use for the fallback `src`; defaults to the
            largest generated width.
        visibility: Visibility for the generated TypeScript target.
    """

    if not widths:
        fail("widths must not be empty")
    if heights != None and len(widths) != len(heights):
        fail("widths and heights must have the same length")

    height_by_width = {}
    for i, width in enumerate(widths):
        if width <= 0:
            fail("widths must be positive")
        if width in height_by_width:
            fail("duplicate width: %d" % width)
        height = None
        if heights != None:
            height = heights[i]
            if height <= 0:
                fail("heights must be positive")
        height_by_width[width] = height

    sorted_widths = sorted(widths)

    if default_width == None:
        default_width = sorted_widths[-1]
    if default_width not in height_by_width:
        fail("default_width must be one of widths")

    assets = {}
    jpeg_export_names = []
    webp_export_names = []
    for width in sorted_widths:
        height = height_by_width[width]
        jpeg_export_name = _variant_export_name("jpeg", width)
        jpeg_export_names.append(jpeg_export_name)
        jpeg_target_name = "%s_%d_jpg" % (name, width)

        transcode_img(
            name = jpeg_target_name,
            src = src,
            output_file_name = "%s_%d.jpg" % (name, width),
            width = width,
            height = height,
            fit = fit,
            crop_scale = crop_scale,
            quality = jpeg_quality,
        )
        assets[":" + jpeg_target_name] = jpeg_export_name

        webp_export_name = _variant_export_name("webp", width)
        webp_export_names.append(webp_export_name)
        webp_target_name = "%s_%d_webp" % (name, width)

        transcode_img(
            name = webp_target_name,
            src = src,
            output_file_name = "%s_%d.webp" % (name, width),
            width = width,
            height = height,
            fit = fit,
            crop_scale = crop_scale,
            quality = webp_quality,
        )
        assets[":" + webp_target_name] = webp_export_name

    sources_module = name + "_sources"
    hashed_public_assets(
        name = name + "_content_addressed",
        outs = [sources_module + ".ts"],
        assets = assets,
        public_dir = public_dir,
    )

    _srcset_module(
        name = name + "_srcset_module",
        out = name + ".ts",
        sources_module = sources_module,
        widths = sorted_widths,
        jpeg_export_names = jpeg_export_names,
        webp_export_names = webp_export_names,
        default_width = default_width,
        sizes = sizes,
    )

    ts_project(
        name = name,
        srcs = [
            ":" + name + "_content_addressed_generated",
            ":" + name + "_srcset_module",
        ],
        visibility = visibility,
    )

def responsive_jpeg_srcset(
        name,
        src,
        widths,
        sizes,
        heights = None,
        quality = 85,
        fit = "contain",
        crop_scale = None,
        public_dir = "sha256",
        default_width = None,
        visibility = None):
    responsive_image_srcset(
        name = name,
        src = src,
        widths = widths,
        sizes = sizes,
        heights = heights,
        jpeg_quality = quality,
        webp_quality = quality,
        fit = fit,
        crop_scale = crop_scale,
        public_dir = public_dir,
        default_width = default_width,
        visibility = visibility,
    )
