"""Rules for content-addressed assets served from a Next.js public directory."""

NextPublicAssetsInfo = provider(
    doc = "Content-addressed files that should be available from the Next public root.",
    fields = {
        "public_assets": "depset of tree artifacts containing digest-keyed public files",
    },
)

_CollectedNextPublicAssetsInfo = provider(
    doc = "Aspect-collected content-addressed files.",
    fields = {
        "public_assets": "depset of tree artifacts containing digest-keyed public files",
    },
)

def _hashed_public_assets_impl(ctx):
    modules = {
        target_name: ctx.actions.declare_file(module_path)
        for target_name, module_path in ctx.attr.modules.items()
    }
    public_dir = ctx.actions.declare_directory(ctx.attr.public_dir)

    exports_by_module = {target_name: [] for target_name in ctx.attr.modules}

    args = ctx.actions.args()
    args.add(public_dir.path)
    args.add(ctx.attr.url_prefix)
    args.add(len(modules))

    for target_name, module in modules.items():
        args.add(module.path)
        args.add(ctx.attr.poster_exports.get(target_name, ""))

    inputs = []
    args.add(len(ctx.attr.assets))
    for target, spec in ctx.attr.assets.items():
        parts = spec.split("|")
        if len(parts) != 2:
            fail("asset spec for %s must be '<module target>|<export name>'" % target.label)

        target_name = parts[0]
        export_name = parts[1]
        if target_name not in modules:
            fail("asset %s references unknown module target %s" % (target.label, target_name))

        files = target.files.to_list()
        if len(files) != 1:
            fail("asset label %s must produce exactly one file" % target.label)

        src = files[0]
        inputs.append(src)
        exports_by_module[target_name].append(export_name)
        args.add(src.path)
        args.add(modules[target_name].path)
        args.add(export_name)

    for target_name, poster_export in ctx.attr.poster_exports.items():
        if target_name not in modules:
            fail("poster_exports references unknown module target %s" % target_name)
        if poster_export not in exports_by_module[target_name]:
            fail("poster export %s is not exported by module target %s" % (poster_export, target_name))

    ctx.actions.run_shell(
        inputs = inputs,
        outputs = modules.values() + [public_dir],
        arguments = [args],
        command = """
set -euo pipefail

public_dir="$1"
url_prefix="$2"
module_count="$3"
shift 3

rm -rf "$public_dir"
mkdir -p "$public_dir"
poster_file="$public_dir/.posters"
: > "$poster_file"

while [ "$module_count" -gt 0 ]; do
  module="$1"
  poster_export="$2"
  shift 2

  {
    echo "// Generated by //ts/next.js:public_assets.bzl"
    echo
  } > "$module"

  if [ -n "$poster_export" ]; then
    printf '%s\\t%s\\n' "$module" "$poster_export" >> "$poster_file"
  fi

  module_count=$((module_count - 1))
done

asset_count="$1"
shift

while [ "$asset_count" -gt 0 ]; do
  src="$1"
  module="$2"
  export_name="$3"
  shift 3

  if command -v sha256sum > /dev/null 2>&1; then
    digest="$(sha256sum "$src" | awk '{print $1}')"
  else
    digest="$(shasum -a 256 "$src" | awk '{print $1}')"
  fi

  if [ ! -e "$public_dir/$digest" ]; then
    cp "$src" "$public_dir/$digest"
  fi
  printf 'export const %s = "%s%s";\\n' "$export_name" "$url_prefix" "$digest" >> "$module"

  asset_count=$((asset_count - 1))
done

while IFS="$(printf '\\t')" read -r module poster_export; do
  if [ -n "$module" ]; then
    printf 'export const poster = { src: %s } as const;\\n' "$poster_export" >> "$module"
  fi
done < "$poster_file"
rm "$poster_file"
""",
    )

    output_groups = {
        "public_assets": depset([public_dir]),
    }
    for target_name, module in modules.items():
        output_groups[target_name] = depset([module])

    return [
        DefaultInfo(files = depset(modules.values())),
        NextPublicAssetsInfo(public_assets = depset([public_dir])),
        OutputGroupInfo(**output_groups),
    ]

_hashed_public_assets = rule(
    implementation = _hashed_public_assets_impl,
    attrs = {
        "assets": attr.label_keyed_string_dict(
            allow_files = True,
            mandatory = True,
        ),
        "modules": attr.string_dict(mandatory = True),
        "poster_exports": attr.string_dict(),
        "public_dir": attr.string(mandatory = True),
        "url_prefix": attr.string(mandatory = True),
    },
)

def hashed_public_assets(name, assets, modules, public_dir, url_prefix, poster_exports = {}):
    """Generate digest-keyed public assets and TypeScript URL manifests.

    Args:
        name: target prefix for the generated asset store.
        assets: dict mapping asset labels to "<module target>|<export name>".
        modules: dict mapping public module target names to generated module paths.
        public_dir: generated public directory path, such as "sha256".
        url_prefix: URL prefix corresponding to public_dir, such as "/sha256/".
        poster_exports: optional dict mapping module target names to poster export names.
    """

    generated = name + "_generated"
    _hashed_public_assets(
        name = generated,
        assets = assets,
        modules = modules,
        poster_exports = poster_exports,
        public_dir = public_dir,
        url_prefix = url_prefix,
    )

    native.filegroup(
        name = name + "_public_assets",
        srcs = [":" + generated],
        output_group = "public_assets",
    )

    for target_name in modules:
        native.filegroup(
            name = target_name,
            srcs = [":" + generated],
            output_group = target_name,
        )

def _collect_public_assets_aspect_impl(target, ctx):
    transitive = []

    if NextPublicAssetsInfo in target:
        transitive.append(target[NextPublicAssetsInfo].public_assets)

    for attr_name in ["srcs", "deps", "data", "assets"]:
        if not hasattr(ctx.rule.attr, attr_name):
            continue

        attr = getattr(ctx.rule.attr, attr_name)
        if type(attr) != type([]):
            attr = [attr]

        for dep in attr:
            if _CollectedNextPublicAssetsInfo in dep:
                transitive.append(dep[_CollectedNextPublicAssetsInfo].public_assets)

    return [_CollectedNextPublicAssetsInfo(public_assets = depset(transitive = transitive))]

_collect_public_assets_aspect = aspect(
    implementation = _collect_public_assets_aspect_impl,
    attr_aspects = ["srcs", "deps", "data", "assets"],
)

def _collect_public_assets_impl(ctx):
    public_dir = ctx.actions.declare_directory(ctx.attr.public_dir)

    transitive = []
    for dep in ctx.attr.deps:
        if _CollectedNextPublicAssetsInfo in dep:
            transitive.append(dep[_CollectedNextPublicAssetsInfo].public_assets)

    public_assets = depset(transitive = transitive)
    args = ctx.actions.args()
    args.add(public_dir.path)
    args.add_all(public_assets, expand_directories = True)

    ctx.actions.run_shell(
        inputs = public_assets,
        outputs = [public_dir],
        arguments = [args],
        command = """
set -euo pipefail

public_dir="$1"
shift

rm -rf "$public_dir"
mkdir -p "$public_dir"

for src in "$@"; do
  [ -f "$src" ] || continue
  dest="$public_dir/$(basename "$src")"
  if [ ! -e "$dest" ]; then
    cp "$src" "$dest"
  fi
done
""",
    )

    return [
        DefaultInfo(files = depset([public_dir])),
    ]

collect_public_assets = rule(
    implementation = _collect_public_assets_impl,
    attrs = {
        "deps": attr.label_list(
            aspects = [_collect_public_assets_aspect],
            mandatory = True,
        ),
        "public_dir": attr.string(mandatory = True),
    },
)
