local_repository(
    name = "rules_rust",
    path = "../../..",
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

# Need to have an http_file along the lines of:
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
# 
# http_file(
#     name = "crate_universe_resolver_darwin",
#     urls = ["file:///PATH/TO/rules_rust/cargo/crate_universe_resolver/target/release/crate_universe_resolver"],
#     sha256 = "FILL_ME_IN",
#     executable = True,
# )
# 
# http_file(
#     name = "crate_universe_resolver_linux",
#     urls = ["file:///PATH/TO/rules_rust/cargo/crate_universe_resolver/target/release/crate_universe_resolver"],
#     sha256 = "FILL_ME_IN",
#     executable = True,
# )

load("@rust_deps//:defs.bzl", "pinned_rust_install")

pinned_rust_install()
