package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"io"
	"mime"
	"os"
	"path/filepath"
	"strconv"
)

const generatedHeader = "// Generated by //ts/next.js:public_assets.bzl\n\n"

func copyFile(dest, src string) error {
	if _, err := os.Stat(dest); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o777); err != nil {
		return err
	}

	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(dest, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o666)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return nil
		}
		return err
	}

	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

func digestFile(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}

func digestFileName(path string) (string, error) {
	digest, err := digestFile(path)
	if err != nil {
		return "", err
	}
	return digest + filepath.Ext(path), nil
}

var decodableImageMIMETypes = map[string]bool{
	"image/gif":  true,
	"image/jpeg": true,
	"image/png":  true,
}

func isDecodableImage(path string) bool {
	return decodableImageMIMETypes[mime.TypeByExtension(filepath.Ext(path))]
}

func averageColorHex(img image.Image) (string, error) {
	bounds := img.Bounds()
	pixelCount := uint64(bounds.Dx()) * uint64(bounds.Dy())
	if pixelCount == 0 {
		return "", fmt.Errorf("cannot average empty image")
	}

	var rSum, gSum, bSum uint64
	for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
		for x := bounds.Min.X; x < bounds.Max.X; x++ {
			r, g, b, _ := img.At(x, y).RGBA()
			rSum += uint64(r)
			gSum += uint64(g)
			bSum += uint64(b)
		}
	}

	toByte := func(sum uint64) uint64 {
		average16 := (sum + pixelCount/2) / pixelCount
		return (average16*255 + 32767) / 65535
	}

	return fmt.Sprintf("#%02x%02x%02x", toByte(rSum), toByte(gSum), toByte(bSum)), nil
}

func averageImageColorHex(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	img, _, err := image.Decode(file)
	if err != nil {
		return "", err
	}

	return averageColorHex(img)
}

func nextCount(args []string, index *int, name string) (int, error) {
	if *index >= len(args) {
		return 0, fmt.Errorf("missing %s count", name)
	}
	count, err := strconv.Atoi(args[*index])
	if err != nil {
		return 0, fmt.Errorf("invalid %s count %q: %w", name, args[*index], err)
	}
	*index = *index + 1
	return count, nil
}

func runGenerate(args []string) error {
	if len(args) < 3 {
		return fmt.Errorf("usage: generate <public-dir> <url-prefix> <module> <asset-count> <src export>...")
	}

	publicDir := args[0]
	urlPrefix := args[1]
	module := args[2]
	index := 3

	if err := os.RemoveAll(publicDir); err != nil {
		return err
	}
	if err := os.MkdirAll(publicDir, 0o777); err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(module), 0o777); err != nil {
		return err
	}
	if err := os.WriteFile(module, []byte(generatedHeader), 0o666); err != nil {
		return err
	}

	assetCount, err := nextCount(args, &index, "asset")
	if err != nil {
		return err
	}
	if len(args[index:]) != assetCount*2 {
		return fmt.Errorf("got %d asset arguments, need %d", len(args[index:]), assetCount*2)
	}

	for i := 0; i < assetCount; i++ {
		src := args[index]
		exportName := args[index+1]
		index += 2

		digestName, err := digestFileName(src)
		if err != nil {
			return err
		}
		if err := copyFile(filepath.Join(publicDir, digestName), src); err != nil {
			return err
		}

		line := fmt.Sprintf("export const %s = %q;\n", exportName, urlPrefix+digestName)
		file, err := os.OpenFile(module, os.O_WRONLY|os.O_APPEND, 0)
		if err != nil {
			return err
		}
		if _, err := file.WriteString(line); err != nil {
			file.Close()
			return err
		}
		if isDecodableImage(src) {
			averageColor, err := averageImageColorHex(src)
			if err != nil {
				file.Close()
				return err
			}
			line := fmt.Sprintf("export const %sAverageColor = %q;\n", exportName, averageColor)
			if _, err := file.WriteString(line); err != nil {
				file.Close()
				return err
			}
		}
		if err := file.Close(); err != nil {
			return err
		}
	}

	return nil
}

func runCollect(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: collect <public-dir> <src>...")
	}

	publicDir := args[0]
	if err := os.RemoveAll(publicDir); err != nil {
		return err
	}
	if err := os.MkdirAll(publicDir, 0o777); err != nil {
		return err
	}

	for _, src := range args[1:] {
		info, err := os.Stat(src)
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			continue
		}
		if err := copyFile(filepath.Join(publicDir, filepath.Base(src)), src); err != nil {
			return err
		}
	}

	return nil
}

func run(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: public_assets <generate|collect> ...")
	}

	switch args[0] {
	case "generate":
		return runGenerate(args[1:])
	case "collect":
		return runCollect(args[1:])
	default:
		return fmt.Errorf("unknown subcommand %q", args[0])
	}
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
