package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
)

const generatedHeader = "// Generated by //ts/next.js:public_assets.bzl\n\n"

func copyFile(dest, src string) error {
	if _, err := os.Stat(dest); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o777); err != nil {
		return err
	}

	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(dest, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o666)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return nil
		}
		return err
	}

	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

func digestFile(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}

func nextCount(args []string, index *int, name string) (int, error) {
	if *index >= len(args) {
		return 0, fmt.Errorf("missing %s count", name)
	}
	count, err := strconv.Atoi(args[*index])
	if err != nil {
		return 0, fmt.Errorf("invalid %s count %q: %w", name, args[*index], err)
	}
	*index = *index + 1
	return count, nil
}

func runGenerate(args []string) error {
	if len(args) < 3 {
		return fmt.Errorf("usage: generate <public-dir> <url-prefix> <module-count> <modules...> <asset-count> <src module export>...")
	}

	publicDir := args[0]
	urlPrefix := args[1]
	index := 2

	moduleCount, err := nextCount(args, &index, "module")
	if err != nil {
		return err
	}
	if len(args[index:]) < moduleCount {
		return fmt.Errorf("got %d module paths, need %d", len(args[index:]), moduleCount)
	}

	modules := args[index : index+moduleCount]
	index += moduleCount

	if err := os.RemoveAll(publicDir); err != nil {
		return err
	}
	if err := os.MkdirAll(publicDir, 0o777); err != nil {
		return err
	}

	for _, module := range modules {
		if err := os.MkdirAll(filepath.Dir(module), 0o777); err != nil {
			return err
		}
		if err := os.WriteFile(module, []byte(generatedHeader), 0o666); err != nil {
			return err
		}
	}

	assetCount, err := nextCount(args, &index, "asset")
	if err != nil {
		return err
	}
	if len(args[index:]) != assetCount*3 {
		return fmt.Errorf("got %d asset arguments, need %d", len(args[index:]), assetCount*3)
	}

	for i := 0; i < assetCount; i++ {
		src := args[index]
		module := args[index+1]
		exportName := args[index+2]
		index += 3

		digest, err := digestFile(src)
		if err != nil {
			return err
		}
		if err := copyFile(filepath.Join(publicDir, digest), src); err != nil {
			return err
		}

		line := fmt.Sprintf("export const %s = %q;\n", exportName, urlPrefix+digest)
		file, err := os.OpenFile(module, os.O_WRONLY|os.O_APPEND, 0)
		if err != nil {
			return err
		}
		if _, err := file.WriteString(line); err != nil {
			file.Close()
			return err
		}
		if err := file.Close(); err != nil {
			return err
		}
	}

	return nil
}

func runCollect(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: collect <public-dir> <src>...")
	}

	publicDir := args[0]
	if err := os.RemoveAll(publicDir); err != nil {
		return err
	}
	if err := os.MkdirAll(publicDir, 0o777); err != nil {
		return err
	}

	for _, src := range args[1:] {
		info, err := os.Stat(src)
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			continue
		}
		if err := copyFile(filepath.Join(publicDir, filepath.Base(src)), src); err != nil {
			return err
		}
	}

	return nil
}

func run(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: public_assets <generate|collect> ...")
	}

	switch args[0] {
	case "generate":
		return runGenerate(args[1:])
	case "collect":
		return runCollect(args[1:])
	default:
		return fmt.Errorf("unknown subcommand %q", args[0])
	}
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
