export const saveStateExample = {
	elementStacks: {
		'720_520_7d4fa4bf-8abd-4d48-921c-39009c8368ad': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '720' as const,
			markedForConsumption: 'False' as const,
			elementId: 'passion' as const,
			lastTablePosY: '520' as const,
			quantity: '1' as const,
		},
		'180_0_0490a073-41c3-40a7-8e1d-90a2c93013cc': {
			lifetimeRemaining: '106' as const,
			lastTablePosX: '180' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '0' as const,
			quantity: '1' as const,
		},
		'0_-130_43fde0e6-7bfe-4043-867e-66daa951240c': {
			lifetimeRemaining: '106' as const,
			lastTablePosX: '0' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'360_-390_1564be7b-2972-4356-bcf5-bbf5ed14ab87': {
			lifetimeRemaining: '46' as const,
			lastTablePosX: '360' as const,
			markedForConsumption: 'False' as const,
			elementId: 'glimmering' as const,
			lastTablePosY: '-390' as const,
			quantity: '1' as const,
		},
		'450_390_40367bf4-f42e-4123-9f6f-e3d17cbf279b': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '450' as const,
			markedForConsumption: 'False' as const,
			mutations: {
				stale: '-1' as const,
			},
			elementId: 'skillpassionc' as const,
			lastTablePosY: '390' as const,
			quantity: '1' as const,
		},
		'810_-130_7e90e91a-0401-4b44-aad3-166957e41d03': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '810' as const,
			markedForConsumption: 'False' as const,
			elementId: 'bequestintro' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'540_0_9f0e09ff-77d5-4c51-bfc0-c830cdf5237f': {
			lifetimeRemaining: '105' as const,
			lastTablePosX: '540' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '0' as const,
			quantity: '1' as const,
		},
		'90_-260_b63016e7-4c24-46b2-9e56-7d3c16420682': {
			lifetimeRemaining: '48' as const,
			lastTablePosX: '90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '-260' as const,
			quantity: '1' as const,
		},
		'450_-130_9ad24ffb-e629-443a-8a01-58a7cfcd5812': {
			lifetimeRemaining: '115' as const,
			lastTablePosX: '450' as const,
			markedForConsumption: 'False' as const,
			elementId: 'fleeting' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'180_-130_cb3c6121-62d0-42ba-8ccf-a3b78a734557': {
			lifetimeRemaining: '115' as const,
			lastTablePosX: '180' as const,
			markedForConsumption: 'False' as const,
			elementId: 'glimmering' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'270.0001_-130_bf593a50-c2ea-4ed7-8014-08ccfec0237e': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '-90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'funds' as const,
			lastTablePosY: '130' as const,
			quantity: '14' as const,
		},
		'540_650_57dc9004-fcaa-457d-b28f-b09aed2a28ec': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '540' as const,
			markedForConsumption: 'False' as const,
			elementId: 'passion' as const,
			lastTablePosY: '650' as const,
			quantity: '1' as const,
		},
		'270_-130_6b13b242-1239-40a2-a645-6473568328a9': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '270' as const,
			markedForConsumption: 'False' as const,
			elementId: 'dropzone' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'0_0_d315439c-bd2d-4b24-8d76-247cb700b27c': {
			lifetimeRemaining: '223' as const,
			lastTablePosX: '0' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '0' as const,
			quantity: '1' as const,
		},
		'90_0_95740fdd-f984-49d3-b9ab-57c14effec5c': {
			lifetimeRemaining: '160' as const,
			lastTablePosX: '90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '0' as const,
			quantity: '1' as const,
		},
		'270_650_3ed2df1b-cb67-40d4-b06a-bde076c2c308': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '-90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'health' as const,
			lastTablePosY: '130' as const,
			quantity: '2' as const,
		},
		'270_520_f29e21f6-721c-4c54-ba2c-b067000766d4': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '-90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'reason' as const,
			lastTablePosY: '130' as const,
			quantity: '4' as const,
		},
		'809.9999_520_577bdd5a-cec4-4b33-88ef-728d09e5d8ac': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '810' as const,
			markedForConsumption: 'False' as const,
			elementId: 'passion' as const,
			lastTablePosY: '520' as const,
			quantity: '1' as const,
		},
		'-90_130_cb3c9e4f-c92f-44db-afd9-529a6751308c': {
			lifetimeRemaining: '134' as const,
			lastTablePosX: '-90' as const,
			markedForConsumption: 'False' as const,
			elementId: 'affliction' as const,
			lastTablePosY: '130' as const,
			quantity: '1' as const,
		},
		'180_520_63bf8be6-65ff-4a7c-abba-f6eec139cee5': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '180' as const,
			markedForConsumption: 'False' as const,
			elementId: 'skillreasonc' as const,
			lastTablePosY: '520' as const,
			quantity: '1' as const,
		},
		'-1080_520_0dc91173-dd35-4e1c-b533-12a87131b77a': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '-1080' as const,
			markedForConsumption: 'False' as const,
			elementId: 'defaulthunter' as const,
			lastTablePosY: '520' as const,
			quantity: '1' as const,
		},
		'270_-390_7c1bd2dc-6399-4a31-9be6-a8b0a3edd5db': {
			lifetimeRemaining: '46' as const,
			lastTablePosX: '270' as const,
			markedForConsumption: 'False' as const,
			elementId: 'glimmering' as const,
			lastTablePosY: '-390' as const,
			quantity: '1' as const,
		},
		'360_130_049042c7-b399-418f-8a74-a3992e88c152': {
			lifetimeRemaining: '160' as const,
			lastTablePosX: '360' as const,
			markedForConsumption: 'False' as const,
			elementId: 'mystique' as const,
			lastTablePosY: '130' as const,
			quantity: '1' as const,
		},
		'360_-130_18b765b8-b4f9-4a04-8ba8-b342208b7da8': {
			lifetimeRemaining: '35' as const,
			lastTablePosX: '360' as const,
			markedForConsumption: 'False' as const,
			elementId: 'restlessness' as const,
			lastTablePosY: '-130' as const,
			quantity: '1' as const,
		},
		'450_650_4987464c-10c9-41a2-a3a6-7b0bb50db956': {
			lifetimeRemaining: '0' as const,
			lastTablePosX: '450' as const,
			markedForConsumption: 'False' as const,
			elementId: 'passion' as const,
			lastTablePosY: '650' as const,
			quantity: '1' as const,
		},
	},
	decks: {
		'deck.explorevaulteveningisles4_success': {
			'2': 'commandspreservationallexistsmandaic' as const,
			'3': 'birdsongphrygian' as const,
			eliminatedCards: [],
			'1': 'scarskyfucine' as const,
			'4': 'toollanternf' as const,
		},
		'deck.explorevaultcontinent1_success': {
			'1': 'toolforgeb' as const,
			'4': 'highmysterieschurchsolarfucine' as const,
			'5': 'ingredientwinterb' as const,
			eliminatedCards: [],
			'2': 'morphycodexaramaic' as const,
			'3': 'bookoftruebloodlatin' as const,
		},
		hunters: {
			'1': 'investigator2' as const,
			'4': 'investigator3' as const,
			'5': 'investigator1' as const,
			eliminatedCards: [],
			'2': 'defaulthunter' as const,
			'3': 'investigator4' as const,
		},
		stagriddles: {
			'1': 'waystagbefore_2' as const,
			'4': 'waystagbefore_3' as const,
			'5': 'waystagbefore_1' as const,
			eliminatedCards: [],
			'2': 'waystagbefore_5' as const,
			'3': 'waystagbefore_4' as const,
		},
		'deck.scout.morbihan': {
			'1': 'op.sea' as const,
			'6': 'op.horned' as const,
			'4': 'op.night' as const,
			'5': 'obscurity' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'op.faith' as const,
		},
		'deck.send.investigate.baghdad': {
			'1': 'city.meshad' as const,
			'4': 'end.messana' as const,
			'5': 'city.tiflis' as const,
			eliminatedCards: [],
			'2': 'city.istanbul' as const,
			'3': 'city.alexandria' as const,
		},
		'deck.scout.marrakech': {
			'13': 'loc.shrine.lionsmith.marrakech' as const,
			'14': 'op.heat' as const,
			'8': 'op.dawn' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.connection.holy' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.villa' as const,
			'15': 'op.warehouse' as const,
			'1': 'op.sunset' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.curio.lantern3' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.office' as const,
			'4': 'op.cats' as const,
			'17': 'op.connection.underworld' as const,
			eliminatedCards: [],
			'16': 'op.faith' as const,
			'18': 'op.echidna' as const,
			'10': 'op.licence.medical' as const,
		},
		'deck.explorevaultcontinent2_success': {
			'1': 'thirstingtantrasanskrit' as const,
			'6': 'ingredientheartb' as const,
			'4': 'tantrawormssanskrit' as const,
			'5': 'dehoris2latin' as const,
			eliminatedCards: [],
			'2': 'textbookaramaic' as const,
			'3': 'againstsisterhoodknotgreek' as const,
		},
		vaultscontinent: {
			'1': 'vaultcontinent3' as const,
			'6': 'vaultcontinent2' as const,
			'4': 'vaultcontinent5' as const,
			'5': 'vaultcontinent4' as const,
			eliminatedCards: [],
			'2': 'vaultcontinent6' as const,
			'3': 'vaultcontinent1' as const,
		},
		'deck.scout.vienna': {
			'8': 'op.office' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.villa' as const,
			'6': 'op.kleidouchos' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.weapon.b' as const,
			'5': 'op.dawn' as const,
			'4': 'op.warehouse' as const,
			eliminatedCards: [],
			'10': 'op.rarity.forge' as const,
		},
		'deck.send.investigate.wilderness': {
			'1': 'end.messana' as const,
			'37': 'city.munich' as const,
			'35': 'city.vienna' as const,
			'8': 'end.paro' as const,
			'9': 'city.rostock' as const,
			'28': 'city.istanbul' as const,
			'2': 'end.slettnes' as const,
			'3': 'city.paris' as const,
			'18': 'city.meshad' as const,
			'6': 'end.cheko' as const,
			'7': 'city.sverdlovsk' as const,
			'4': 'city.leningrad' as const,
			'5': 'city.tripoli' as const,
			'36': 'city.stalingrad' as const,
			'38': 'city.london' as const,
			'24': 'city.algiers' as const,
			'34': 'city.granada' as const,
			'25': 'end.ghardaia' as const,
			'14': 'city.prague' as const,
			'15': 'end.morbihan' as const,
			'40': 'city.budapest' as const,
			'20': 'end.bornholm' as const,
			'30': 'city.candia' as const,
			'21': 'city.kiev' as const,
			'10': 'city.marrakech' as const,
			'26': 'city.krakow' as const,
			'11': 'city.baghdad' as const,
			'27': 'city.venice' as const,
			'16': 'city.tirana' as const,
			eliminatedCards: [],
			'17': 'city.amsterdam' as const,
			'33': 'city.tiflis' as const,
			'22': 'city.cluj' as const,
			'32': 'city.aachen' as const,
			'23': 'city.samarkand' as const,
			'12': 'city.kaunas' as const,
			'13': 'city.avignon' as const,
			'31': 'city.alexandria' as const,
			'29': 'city.nizhny' as const,
			'39': 'city.valletta' as const,
			'19': 'city.strasbourg' as const,
		},
		vaultslandbeyondforest: {
			'1': 'vaultlandbeyondforest2' as const,
			'4': 'vaultlandbeyondforest3' as const,
			'5': 'vaultlandbeyondforest1' as const,
			eliminatedCards: [],
			'2': 'vaultlandbeyondforest5' as const,
			'3': 'vaultlandbeyondforest4' as const,
		},
		'deck.send.investigate.samarkand.turmoil': {
			'2': 'city.tiflis' as const,
			'3': 'city.meshad' as const,
			eliminatedCards: [],
			'1': 'city.sverdlovsk' as const,
			'4': 'end.paro' as const,
		},
		'deck.scout.venice': {
			'13': 'op.townhouse' as const,
			'14': 'op.office' as const,
			'8': 'op.connection.underworld' as const,
			'9': 'op.villa' as const,
			'11': 'op.warehouse' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.licence.medical' as const,
			'1': 'op.connection.holy' as const,
			'6': 'op.dawn' as const,
			'7': 'op.cats' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.curio.knock' as const,
			'4': 'loc.shrine.lionsmith.venice' as const,
			eliminatedCards: [],
			'10': 'op.faith' as const,
		},
		mansus_wood1: {
			'2': 'rumour' as const,
			'3': 'fragmentsecrethistoriesb' as const,
			eliminatedCards: [],
			'1': 'influencegrail' as const,
			'4': 'vitality' as const,
		},
		'deck.send.investigate.nizhny.turmoil': {
			'2': 'city.munich' as const,
			'3': 'city.prague' as const,
			eliminatedCards: [],
			'1': 'city.amsterdam' as const,
			'4': 'city.paris' as const,
		},
		'deck.send.investigate.samarkand': {
			'2': 'city.tiflis' as const,
			'3': 'city.meshad' as const,
			eliminatedCards: [],
			'1': 'city.sverdlovsk' as const,
			'4': 'end.paro' as const,
		},
		'deck.scout.candia': {
			'13': 'op.licence.import' as const,
			'14': 'loc.shrine.colonel.candia' as const,
			'8': 'op.office' as const,
			'9': 'op.connection.official' as const,
			'11': 'op.horned' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.warehouse' as const,
			'15': 'op.curio.heart' as const,
			'1': 'op.sea' as const,
			'6': 'op.dawn' as const,
			'7': 'op.sea' as const,
			'12': 'op.villa' as const,
			'5': 'op.connection.underworld' as const,
			'4': 'op.heights' as const,
			eliminatedCards: [],
			'16': 'op.townhouse' as const,
			'10': 'op.heat' as const,
		},
		'deck.send.investigate.meshad': {
			'2': 'city.baghdad' as const,
			'3': 'end.messana' as const,
			eliminatedCards: [],
			'1': 'city.samarkand' as const,
			'4': 'end.paro' as const,
		},
		'deck.scout.baghdad': {
			'13': 'op.licence.medical' as const,
			'8': 'op.heat' as const,
			'9': 'op.connection.holy' as const,
			'11': 'op.curio.forge' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.ruler' as const,
			'6': 'op.connection.radicals' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.faith' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.send.investigate.istanbul.turmoil': {
			'2': 'city.tirana' as const,
			'3': 'city.alexandria' as const,
			eliminatedCards: [],
			'1': 'city.cluj' as const,
			'4': 'city.baghdad' as const,
		},
		acquaintances: {
			'1': 'generic_a_knock' as const,
			'8': 'generic_a_moth' as const,
			'9': 'violet_a' as const,
			'28': 'elridge_a' as const,
			'2': 'generic_a_winter' as const,
			'3': 'sylvia_a' as const,
			'18': 'cat_a' as const,
			'6': 'generic_a_grail' as const,
			'7': 'dorothy_a' as const,
			'4': 'slee_a' as const,
			'5': 'leo_a' as const,
			'24': 'enid_a' as const,
			'25': 'generic_a_edge' as const,
			'14': 'rose_a' as const,
			'15': 'porter_a' as const,
			'20': 'generic_a_heart' as const,
			'21': 'clifton_a' as const,
			'10': 'laidlaw_a' as const,
			'26': 'clovette_a' as const,
			'11': 'auclair_a' as const,
			'27': 'renira_a' as const,
			'16': 'tristan_a' as const,
			eliminatedCards: [],
			'17': 'generic_a_forge' as const,
			'22': 'victor_a' as const,
			'23': 'saliba_a' as const,
			'12': 'valciane_a' as const,
			'13': 'generic_a_lantern' as const,
			'29': 'neville_a' as const,
			'19': 'ysabet_a' as const,
		},
		'deck.send.investigate.tiflis.turmoil': {
			'2': 'city.cluj' as const,
			'3': 'city.baghdad' as const,
			eliminatedCards: [],
			'1': 'city.stalingrad' as const,
			'4': 'city.samarkand' as const,
		},
		'deck.scout.cluj': {
			'13': 'op.warehouse' as const,
			'14': 'op.licence.medical' as const,
			'8': 'op.connection.official' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.ruler' as const,
			'6': 'op.dawn' as const,
			'7': 'op.sunset' as const,
			'12': 'op.rarity.winter' as const,
			'5': 'op.weapon.b' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.heights' as const,
		},
		roserewards: {
			'2': 'fleeting' as const,
			'3': 'memorypassionate' as const,
			eliminatedCards: [],
			'1': 'memorybittersweet' as const,
			'4': 'memorypleasant' as const,
		},
		'deck.long.executestrategy.assassination.begin': {
			'2': 'assassinationinprogress.follower' as const,
			'1': 'assassinationinprogress.player' as const,
			eliminatedCards: [],
		},
		mansus_stagdoor: {
			'2': 'fragmentsecrethistoriesc' as const,
			'3': 'influenceknocke' as const,
			'1': 'influenceforgec' as const,
			eliminatedCards: [],
		},
		mansus_spiderdoor1: {
			'2': 'influencelanterne' as const,
			'3': 'ingredientforgef' as const,
			eliminatedCards: [],
			'1': 'influenceforgeg' as const,
			'4': 'fragmentsecrethistoriese' as const,
		},
		'deck.send.investigate.sverdlovsk': {
			'1': 'end.paro' as const,
			'4': 'city.samarkand' as const,
			'5': 'end.cheko' as const,
			eliminatedCards: [],
			'2': 'city.nizhny' as const,
			'3': 'city.stalingrad' as const,
		},
		'deck.send.investigate.nizhny': {
			'2': 'city.leningrad' as const,
			'3': 'city.stalingrad' as const,
			eliminatedCards: [],
			'1': 'end.cheko' as const,
			'4': 'city.sverdlovsk' as const,
		},
		'deck.explorevaultloneandlevelsands1_success': {
			'2': 'manneralchemistsparedvak' as const,
			'3': 'medusaslamentgreek' as const,
			eliminatedCards: [],
			'1': 'toollanternd' as const,
			'4': 'focusambermandaic' as const,
		},
		commontomes: {
			'1': 'textbookreason' as const,
			'8': 'textbookreason' as const,
			'9': 'burningofunburntgod' as const,
			'28': 'onthewhite' as const,
			'2': 'textbookpassion' as const,
			'3': 'queensoftherivers' as const,
			'18': 'travellingatnight2' as const,
			'6': 'textbookreason' as const,
			'7': 'victoryofcrowns' as const,
			'4': 'locksmithsdream1' as const,
			'5': 'raptintheking' as const,
			'24': 'waroftheroadscensored' as const,
			'25': 'apolloandmarsyas' as const,
			'14': 'kitlingripe' as const,
			'15': 'introductiontohistories' as const,
			'20': 'textbookpassion' as const,
			'30': 'vienneseconundra' as const,
			'21': 'sixlettersonnecessity' as const,
			'10': 'humoursofagentleman' as const,
			'26': 'textbookgreek' as const,
			'11': 'travellingatnight1' as const,
			'27': 'orchidtransfigurations1latin' as const,
			'16': 'orchidtransfigurations2latin' as const,
			eliminatedCards: [],
			'17': 'textbooksanskrit' as const,
			'22': 'textbooklatin' as const,
			'23': 'dehoris1latin' as const,
			'12': 'skeletonsongs' as const,
			'13': 'textbookpassion' as const,
			'29': 'locksmithsdream2' as const,
			'19': 'onwhatiscontainedbysilvergreek' as const,
		},
		'deck.send.investigate.amsterdam': {
			'2': 'city.london' as const,
			'3': 'city.rostock' as const,
			eliminatedCards: [],
			'1': 'end.bornholm' as const,
			'4': 'city.aachen' as const,
		},
		'deck.send.investigate.algiers.turmoil': {
			'1': 'city.valletta' as const,
			'4': 'city.tripoli' as const,
			'5': 'city.avignon' as const,
			eliminatedCards: [],
			'2': 'city.marrakech' as const,
			'3': 'end.ghardaia' as const,
		},
		'deck.explorevaulteveningisles3_success': {
			'2': 'ingredientgrailf' as const,
			'3': 'toolknockf' as const,
			eliminatedCards: [],
			'1': 'bookextinguishedheartmandaic' as const,
			'4': 'bookwhitecatphrygian' as const,
		},
		'deck.send.investigate.paris': {
			'2': 'end.morbihan' as const,
			'3': 'city.strasbourg' as const,
			eliminatedCards: [],
			'1': 'city.london' as const,
			'4': 'city.aachen' as const,
		},
		'deck.work.seance.unexpected': {
			'13': 'glimmeringplus' as const,
			'14': 'eruditionplus' as const,
			'8': 'dread' as const,
			'9': 'fascination' as const,
			'11': 'fragmentsecrethistories' as const,
			'2': 'influencemothe' as const,
			'3': 'vitalityplus' as const,
			'15': 'influencewinterc' as const,
			'1': 'influencemothc' as const,
			'6': 'influencewinterc' as const,
			'7': 'fragmentsecrethistoriesc' as const,
			'12': 'influencelanternc' as const,
			'5': 'influencelanternc' as const,
			'4': 'vitalityplus' as const,
			'19': 'glimmeringplus' as const,
			'17': 'influencemothc' as const,
			eliminatedCards: [],
			'16': 'dread' as const,
			'20': 'fascination' as const,
			'18': 'eruditionplus' as const,
			'10': 'fragmentsecrethistories' as const,
		},
		'rkx.weaknesses.disfavour': {
			'2': 'rkx.weakness.wolf.hidden' as const,
			'3': 'rkx.weakness.horned.hidden' as const,
			'1': 'rkx.weakness.flowermaker.hidden' as const,
			eliminatedCards: [],
		},
		'deck.explorevaulteveningisles2_success': {
			'2': 'ingredientheartf' as const,
			'3': 'timedivisionmandaic' as const,
			eliminatedCards: [],
			'1': 'bighufffucine' as const,
			'4': 'toolforgef' as const,
		},
		'deck.scout.messana': {
			'1': 'op.horned' as const,
			'6': 'op.heights' as const,
			'4': 'op.sunset' as const,
			'5': 'obscurity' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'op.heat' as const,
		},
		'deck.explorevaultlandbeyondforest5_success': {
			'1': 'knownunknowntantrasanskrit' as const,
			'6': 'encirclingtantrasanskrit' as const,
			'4': 'silverbookfucine' as const,
			'5': 'ironbookfucine' as const,
			eliminatedCards: [],
			'2': 'matthiasamethystpursuitaramaic' as const,
			'3': 'burningwomanphrygian' as const,
		},
		mansus_spiderdoor: {
			'2': 'favour' as const,
			'3': 'fragmentsecrethistoriesd' as const,
			eliminatedCards: [],
			'1': 'influencegraile' as const,
			'4': 'influencehearte' as const,
		},
		'deck.explorevaultloneandlevelsands4_success': {
			'1': 'influencewintere' as const,
			'4': 'toolknockd' as const,
			'5': 'ingredientwinterf' as const,
			eliminatedCards: [],
			'2': 'toolwinterf' as const,
			'3': 'memoryofgodsfucine' as const,
		},
		'deck.explorevaultcontinent3_success': {
			'2': 'inthemountainsasupontheplainvak' as const,
			'3': 'toolmothd' as const,
			eliminatedCards: [],
			'1': 'ingredientmothd' as const,
			'4': 'toolgrailmoth' as const,
		},
		mansus_whitedoor1: {
			'1': 'glimmering' as const,
			'6': 'fragmentsecrethistoriesc' as const,
			'4': 'fascination' as const,
			'5': 'erudition' as const,
			eliminatedCards: [],
			'2': 'favour' as const,
			'3': 'influenceknockc' as const,
		},
		mansus_whitedoor2: {
			'2': 'fragmentsecrethistoriesc' as const,
			'3': 'influenceheartc' as const,
			eliminatedCards: [],
			'1': 'influencelanternc' as const,
			'4': 'glimmering' as const,
		},
		'deck.send.investigate.sverdlovsk.turmoil': {
			'1': 'end.paro' as const,
			'4': 'city.samarkand' as const,
			'5': 'end.cheko' as const,
			eliminatedCards: [],
			'2': 'city.nizhny' as const,
			'3': 'city.stalingrad' as const,
		},
		'priest.repevent': {
			'8': 'mystique' as const,
			'9': 'mystique' as const,
			'11': 'mystique' as const,
			'2': 'funds' as const,
			'3': 'notoriety' as const,
			'1': 'funds' as const,
			'6': 'funds' as const,
			'7': 'notoriety' as const,
			'12': 'notoriety' as const,
			'5': 'funds' as const,
			'4': 'mystique' as const,
			eliminatedCards: [],
			'10': 'notoriety' as const,
		},
		vaultsrendingmountains: {
			'2': 'vaultrendingmountains4' as const,
			'3': 'vaultrendingmountains3' as const,
			eliminatedCards: [],
			'1': 'vaultrendingmountains1' as const,
			'4': 'vaultrendingmountains2' as const,
		},
		'deck.talk.ghoul.memory.menacing': {
			'1': 'influenceedgec' as const,
			'4': 'influencewinterc' as const,
			'5': 'vitalityplus' as const,
			eliminatedCards: [],
			'2': 'influencewinterc' as const,
			'3': 'influenceedgec' as const,
		},
		'deck.send.investigate.aachen': {
			'2': 'city.munich' as const,
			'3': 'city.prague' as const,
			eliminatedCards: [],
			'1': 'city.amsterdam' as const,
			'4': 'city.paris' as const,
		},
		exploreevents: {
			'2': 'dayplaces' as const,
			'3': 'daycriminals' as const,
			eliminatedCards: [],
			'1': 'daycriminals' as const,
			'4': 'dayplaces' as const,
		},
		'deck.explorevaultrendingmountains3_success': {
			'2': 'toolknockd' as const,
			'3': 'bookofmasksphrygian' as const,
			eliminatedCards: [],
			'1': 'toollanternfcracked' as const,
			'4': 'larquebinecodexphrygian' as const,
		},
		'deck.send.investigate.leningrad': {
			'2': 'city.kaunas' as const,
			'3': 'city.kiev' as const,
			eliminatedCards: [],
			'1': 'end.slettnes' as const,
			'4': 'city.nizhny' as const,
		},
		locationscapital: {
			'1': 'vaultcapital2' as const,
			'4': 'vaultcapital3' as const,
			'5': 'vaultcapital1' as const,
			eliminatedCards: [],
			'2': 'vaultcapital5' as const,
			'3': 'vaultcapital4' as const,
		},
		'deck.send.investigate.budapest': {
			'2': 'city.venice' as const,
			'3': 'city.tirana' as const,
			eliminatedCards: [],
			'1': 'city.krakow' as const,
			'4': 'city.cluj' as const,
		},
		'deck.scout.istanbul': {
			'13': 'op.connection.radicals' as const,
			'14': 'op.connection.holy' as const,
			'8': 'op.dawn' as const,
			'9': 'op.heat' as const,
			'11': 'op.sea' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.heights' as const,
			'15': 'op.warehouse' as const,
			'1': 'op.sunset' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.curio.lantern1' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.office' as const,
			'4': 'op.sea' as const,
			'17': 'op.connection.underworld' as const,
			eliminatedCards: [],
			'16': 'op.cats' as const,
			'18': 'op.faith' as const,
			'10': 'op.licence.import' as const,
		},
		'deck.send.investigate.strasbourg': {
			'2': 'end.morbihan' as const,
			'3': 'city.granada' as const,
			eliminatedCards: [],
			'1': 'city.paris' as const,
			'4': 'city.aachen' as const,
		},
		'deck.explorevaultcapital1_success': {
			'1': 'textbookfucine' as const,
			'4': 'travellingatnight3' as const,
			'5': 'wainscothistories' as const,
			eliminatedCards: [],
			'2': 'treatiseonunderplaces' as const,
			'3': 'locksmithsdream4' as const,
		},
		'long.strategies.preference.assault': {
			'1': 'strategy.assault.concealed' as const,
			'4': 'strategy.intrigue.concealed' as const,
			'5': 'strategy.assault.concealed' as const,
			eliminatedCards: [],
			'2': 'strategy.downtime.concealed' as const,
			'3': 'strategy.dreams.concealed' as const,
		},
		'deck.explorevaultlandbeyondforest2_success': {
			'1': 'catalogueofunchartedpleasuresphrygian' as const,
			'6': 'gospelzacchaeusgreek' as const,
			'4': 'twentysixenticementsseventormentsfucine' as const,
			'5': 'bookofthronesphrygian' as const,
			eliminatedCards: [],
			'2': 'toolheartd' as const,
			'3': 'influencegrailc' as const,
		},
		'deck.scout.strasbourg': {
			'8': 'op.office' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.villa' as const,
			'6': 'op.horned' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.weapon.b' as const,
			'5': 'op.dawn' as const,
			'4': 'op.warehouse' as const,
			eliminatedCards: [],
			'10': 'op.rarity.knock' as const,
		},
		paintingresultsreputation: {
			'13': 'funds' as const,
			'14': 'mystique' as const,
			'8': 'mystique' as const,
			'9': 'mystique' as const,
			'11': 'overexposure' as const,
			'2': 'funds' as const,
			'3': 'funds' as const,
			'15': 'funds' as const,
			'1': 'funds' as const,
			'6': 'mystique' as const,
			'7': 'funds' as const,
			'12': 'funds' as const,
			'5': 'funds' as const,
			'4': 'funds' as const,
			'17': 'overexposure' as const,
			eliminatedCards: [],
			'16': 'overexposure' as const,
			'18': 'funds' as const,
			'10': 'funds' as const,
		},
		mansus_wood2: {
			'2': 'rumour' as const,
			'3': 'fragmentsecrethistoriesb' as const,
			eliminatedCards: [],
			'1': 'influenceknock' as const,
			'4': 'influenceheart' as const,
		},
		'deck.scout.nizhny': {
			'8': 'op.office' as const,
			'9': 'op.cold' as const,
			'11': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.official' as const,
			'1': 'loc.shrine.colonel.nizhny' as const,
			'6': 'op.sunset' as const,
			'7': 'op.curio.forge' as const,
			'12': 'op.connection.underworld' as const,
			'5': 'op.dawn' as const,
			'4': 'op.warehouse' as const,
			eliminatedCards: [],
			'10': 'op.connection.radicals' as const,
		},
		'deck.talk.ghoul.memory.shameful': {
			'1': 'contentment' as const,
			'4': 'influencegrailc' as const,
			'5': 'favour' as const,
			eliminatedCards: [],
			'2': 'influencegrailc' as const,
			'3': 'influencegrailc' as const,
		},
		'deck.scout.leningrad': {
			'8': 'op.warehouse' as const,
			'9': 'loc.shrine.colonel.leningrad' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.radicals' as const,
			'6': 'op.sunset' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.weapon.b' as const,
			'5': 'op.dawn' as const,
			'4': 'op.cold' as const,
			eliminatedCards: [],
			'10': 'op.licence.medical' as const,
		},
		'deck.explorevaultshires5_success': {
			'1': 'concursumdiariesphrygian' as const,
			'4': 'thosewhodonotsleepfucine' as const,
			'5': 'shavenlocktantrasanskrit' as const,
			eliminatedCards: [],
			'2': 'textbooklatin' as const,
			'3': 'matthiasamethystlossaramaic' as const,
		},
		'deck.send.investigate.prague': {
			'2': 'city.aachen' as const,
			'3': 'city.vienna' as const,
			eliminatedCards: [],
			'1': 'city.rostock' as const,
			'4': 'city.kaunas' as const,
		},
		'deck.explorevaultlandbeyondforest3_success': {
			'1': 'historyofshadowlesskingsaramaic' as const,
			'6': 'erudition' as const,
			'7': 'sunsetpassageslatin' as const,
			'4': 'ingredientgrailf' as const,
			'5': 'ivorybookfucine' as const,
			eliminatedCards: [],
			'2': 'textbooksanskrit' as const,
			'3': 'jumble' as const,
		},
		mansus_peacockdoor: {
			'2': 'fascination' as const,
			'3': 'influencelanterng' as const,
			eliminatedCards: [],
			'1': 'scholarvak' as const,
			'4': 'fragmentsecrethistoriese' as const,
		},
		'long.strategies': {
			'2': 'strategy.downtime.concealed' as const,
			'3': 'strategy.dreams.concealed' as const,
			eliminatedCards: [],
			'1': 'strategy.assault.concealed' as const,
			'4': 'strategy.intrigue.concealed' as const,
		},
		hirelings: {
			'13': 'thugmothminor' as const,
			'14': 'thugmoth' as const,
			'8': 'thugedgeminor' as const,
			'9': 'thugforgeedge' as const,
			'11': 'thugmothminor' as const,
			'2': 'thugedgeminor' as const,
			'3': 'thuglanternmoth' as const,
			'15': 'thugedge' as const,
			'1': 'thugedgeminor' as const,
			'6': 'thugedgeminor' as const,
			'7': 'thugedge' as const,
			'12': 'thugforgeedge' as const,
			'5': 'thugmoth' as const,
			'4': 'thugmothminor' as const,
			'17': 'thuglanternmoth' as const,
			eliminatedCards: [],
			'16': 'thugmothminor' as const,
			'18': 'thugknock' as const,
			'10': 'thugknock' as const,
		},
		'deck.scout.krakow': {
			'13': 'op.licence.medical' as const,
			'8': 'op.townhouse' as const,
			'9': 'op.heights' as const,
			'11': 'op.curio.lantern2' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.faith' as const,
			'6': 'op.connection.holy' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.scout.samarkand': {
			'13': 'op.warehouse' as const,
			'14': 'op.licence.medical' as const,
			'8': 'op.connection.underworld' as const,
			'9': 'loc.shrine.lionsmith.samarkand' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.connection.radicals' as const,
			'1': 'op.cats' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.dawn' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.curio.lantern1' as const,
			'4': 'op.faith' as const,
			eliminatedCards: [],
			'10': 'op.connection.holy' as const,
		},
		seasonevents: {
			'1': 'seasonvisions' as const,
			'6': 'seasonsilence' as const,
			'4': 'seasonsuspicion' as const,
			'5': 'seasonardours' as const,
			eliminatedCards: [],
			'2': 'seasonsuspicion' as const,
			'3': 'seasondespair' as const,
		},
		'deck.scout.avignon': {
			'8': 'op.office' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.rarity.heart' as const,
			'1': 'op.villa' as const,
			'6': 'op.sunset' as const,
			'7': 'op.curio.grail' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.dawn' as const,
			'4': 'op.warehouse' as const,
			eliminatedCards: [],
			'10': 'op.connection.underworld' as const,
		},
		'deck.send.investigate.vienna': {
			'2': 'city.munich' as const,
			'3': 'city.venice' as const,
			eliminatedCards: [],
			'1': 'city.prague' as const,
			'4': 'city.krakow' as const,
		},
		'deck.explorevaultcapital4_success': {
			'1': 'ingredientheartb' as const,
			'4': 'locksmithsdream3' as const,
			'5': 'toolgrailb' as const,
			eliminatedCards: [],
			'2': 'hq.hospital.potential' as const,
			'3': 'roseofhypatiagreek' as const,
		},
		'deck.scout.slettnes': {
			'1': 'op.sea' as const,
			'6': 'op.wolf' as const,
			'4': 'op.sunset' as const,
			'5': 'obscurity' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'op.cold' as const,
		},
		'deck.send.investigate.marrakech': {
			'2': 'end.morbihan' as const,
			'3': 'end.ghardaia' as const,
			eliminatedCards: [],
			'1': 'city.granada' as const,
			'4': 'city.algiers' as const,
		},
		cabaretevents: {
			'1': 'vitality' as const,
			'6': 'notoriety' as const,
			'7': 'fascination' as const,
			'4': 'erudition' as const,
			'5': 'influencegrail' as const,
			eliminatedCards: [],
			'8': 'glimmering' as const,
			'9': 'contentment' as const,
			'11': 'contentment' as const,
			'10': 'fascination' as const,
			'2': 'influencemoth' as const,
			'3': 'contentment' as const,
		},
		'ghoul.memory': {
			'13': 'memory.shameful' as const,
			'8': 'memory.profitable' as const,
			'9': 'memory.menacing' as const,
			'11': 'memory.unexpected' as const,
			'2': 'memory.menacing' as const,
			'3': 'memory.profitable' as const,
			'1': 'memory.joyful' as const,
			'6': 'memory.profitable' as const,
			'7': 'memory.joyful' as const,
			'12': 'memory.joyful' as const,
			'5': 'memory.shameful' as const,
			'4': 'memory.shameful' as const,
			eliminatedCards: [],
			'10': 'memory.menacing' as const,
		},
		'deck.send.investigate.algiers': {
			'1': 'city.valletta' as const,
			'4': 'city.tripoli' as const,
			'5': 'city.avignon' as const,
			eliminatedCards: [],
			'2': 'city.marrakech' as const,
			'3': 'end.ghardaia' as const,
		},
		'deck.scout.london': {
			'8': 'op.warehouse' as const,
			'9': 'op.sea' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.official' as const,
			'1': 'op.sea' as const,
			'6': 'op.connection.radicals' as const,
			'7': 'op.curio.lantern2' as const,
			'12': 'op.connection.underworld' as const,
			'5': 'op.dawn' as const,
			'4': 'op.sulochana' as const,
			eliminatedCards: [],
			'10': 'op.licence.import' as const,
		},
		'deck.explorevaultloneandlevelsands2_success': {
			'1': 'voyagesfofucine' as const,
			'4': 'toolmothf' as const,
			'5': 'toolsecrethistoriesd' as const,
			eliminatedCards: [],
			'2': 'ingredientknockf' as const,
			'3': 'ingredientmothf' as const,
		},
		troublemakerconversations: {
			'1': 'erudition' as const,
			'6': 'fascination' as const,
			'7': 'erudition' as const,
			'4': 'glimmering' as const,
			'5': 'erudition' as const,
			'8': 'dread' as const,
			'9': 'dread' as const,
			eliminatedCards: [],
			'2': 'glimmering' as const,
			'3': 'fascination' as const,
		},
		bechetcommissions: {
			'1': 'commissionarticlegrailc' as const,
			'6': 'commissionarticleforgec' as const,
			'7': 'commissionarticlegrailb' as const,
			'4': 'commissionarticlemothb' as const,
			'5': 'commissionarticlemoth' as const,
			'8': 'commissionarticleforge' as const,
			'9': 'commissionarticleforgeb' as const,
			eliminatedCards: [],
			'2': 'commissionarticlemothc' as const,
			'3': 'commissionarticlegrail' as const,
		},
		'deck.talk.ghoul.memory.profitable': {
			'1': 'funds' as const,
			'4': 'compensation' as const,
			'5': 'jumble' as const,
			eliminatedCards: [],
			'2': 'funds' as const,
			'3': 'funds' as const,
		},
		'deck.scout.algiers': {
			'13': 'op.cats' as const,
			'14': 'op.weapon.d' as const,
			'8': 'op.sea' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.heat' as const,
			'2': 'op.dawn' as const,
			'3': 'op.villa' as const,
			'15': 'op.warehouse' as const,
			'1': 'op.sea' as const,
			'6': 'op.connection.radicals' as const,
			'7': 'op.curio.forge' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.office' as const,
			'4': 'op.heights' as const,
			'17': 'op.connection.underworld' as const,
			eliminatedCards: [],
			'16': 'loc.shrine.lionsmith.algiers' as const,
			'18': 'op.weapon.a' as const,
			'10': 'op.licence.import' as const,
		},
		'deck.send.investigate.alexandria': {
			'2': 'city.candia' as const,
			'3': 'end.messana' as const,
			eliminatedCards: [],
			'1': 'city.istanbul' as const,
			'4': 'city.baghdad' as const,
		},
		'deck.send.investigate.baghdad.turmoil': {
			'1': 'city.meshad' as const,
			'4': 'end.messana' as const,
			'5': 'city.tiflis' as const,
			eliminatedCards: [],
			'2': 'city.istanbul' as const,
			'3': 'city.alexandria' as const,
		},
		'deck.explorevaultcontinent4_success': {
			'1': 'watchfultantrasanskrit' as const,
			'6': 'toolsecrethistoriesb' as const,
			'7': 'influencemothc' as const,
			'4': 'geminiadfucine' as const,
			'5': 'vinzantinscriptionsphrygian' as const,
			eliminatedCards: [],
			'2': 'textbookaramaic' as const,
			'3': 'jumble' as const,
		},
		lanternlong: {
			'2': 'diarist_unknown' as const,
			'3': 'julian_unknown' as const,
			'1': 'diarist_unknown' as const,
			eliminatedCards: [],
		},
		'deck.scout.cheko': {
			'1': 'op.wolf' as const,
			'6': 'op.cats' as const,
			'4': 'op.night' as const,
			'5': 'obscurity' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'op.cold' as const,
		},
		forgelong: {
			'2': 'welland_unknown' as const,
			'3': 'julian_unknown' as const,
			'1': 'welland_unknown' as const,
			eliminatedCards: [],
		},
		'deck.explorevaultrendingmountains4_success': {
			'1': 'ingredientwinterd' as const,
			'6': 'ingredientwinterd' as const,
			'4': 'asthesunhiscoursearamaic' as const,
			'5': 'secondglorymandaic' as const,
			eliminatedCards: [],
			'2': 'textbookphrygiangreek' as const,
			'3': 'ingredientwinterd' as const,
		},
		'deck.send.investigate.krakow': {
			'2': 'city.vienna' as const,
			'3': 'city.budapest' as const,
			eliminatedCards: [],
			'1': 'city.kaunas' as const,
			'4': 'city.kiev' as const,
		},
		'deck.send.investigate.aachen.turmoil': {
			'2': 'city.munich' as const,
			'3': 'city.prague' as const,
			eliminatedCards: [],
			'1': 'city.amsterdam' as const,
			'4': 'city.paris' as const,
		},
		aladimcommissions: {
			'1': 'commissionarticlesecrethistoriesc' as const,
			'6': 'commissionarticlesecrethistoriesb' as const,
			'4': 'commissionarticlelanternb' as const,
			'5': 'commissionarticlelantern' as const,
			eliminatedCards: [],
			'2': 'commissionarticlelanternc' as const,
			'3': 'commissionarticlesecrethistories' as const,
		},
		'deck.send.investigate.avignon': {
			'2': 'city.granada' as const,
			'3': 'city.algiers' as const,
			eliminatedCards: [],
			'1': 'city.munich' as const,
			'4': 'city.venice' as const,
		},
		janningscommissions: {
			'1': 'commissionarticleedgec' as const,
			'6': 'commissionarticleedgeb' as const,
			'4': 'commissionarticleheartb' as const,
			'5': 'commissionarticleheart' as const,
			eliminatedCards: [],
			'2': 'commissionarticleheartc' as const,
			'3': 'commissionarticleedge' as const,
		},
		paintingresultsbasic: {
			'2': 'glimmering' as const,
			'1': 'glimmering' as const,
			eliminatedCards: [],
		},
		'deck.send.investigate.kaunas': {
			'1': 'city.leningrad' as const,
			'4': 'city.krakow' as const,
			'5': 'end.slettnes' as const,
			eliminatedCards: [],
			'2': 'city.rostock' as const,
			'3': 'city.prague' as const,
		},
		'deck.explorevaultshires3_success': {
			'1': 'influencewinterc' as const,
			'6': 'tooledgeb' as const,
			'4': 'ingredientmothb' as const,
			'5': 'ingredientwinterb' as const,
			eliminatedCards: [],
			'2': 'bookofcentipedegreek' as const,
			'3': 'toolwinterb' as const,
		},
		'deck.send.investigate.stalingrad.turmoil': {
			'2': 'city.kiev' as const,
			'3': 'city.tiflis' as const,
			eliminatedCards: [],
			'1': 'city.nizhny' as const,
			'4': 'city.sverdlovsk' as const,
		},
		'deck.scout.meshad': {
			'13': 'loc.shrine.lionsmith.meshad' as const,
			'14': 'op.office' as const,
			'8': 'op.warehouse' as const,
			'9': 'op.connection.underworld' as const,
			'11': 'op.curio.forge' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.townhouse' as const,
			'15': 'op.heat' as const,
			'1': 'op.sunset' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.dawn' as const,
			'12': 'op.cats' as const,
			'5': 'op.licence.medical' as const,
			'4': 'op.connection.holy' as const,
			'17': 'op.villa' as const,
			eliminatedCards: [],
			'16': 'op.connection.official' as const,
			'10': 'op.faith' as const,
		},
		'deck.scout.alexandria': {
			'13': 'op.connection.underworld' as const,
			'14': 'op.cats' as const,
			'8': 'op.curio.lantern1' as const,
			'9': 'op.sea' as const,
			'11': 'op.office' as const,
			'2': 'op.dawn' as const,
			'3': 'op.weapon.a' as const,
			'15': 'loc.shrine.lionsmith.alexandria' as const,
			'1': 'op.sea' as const,
			'6': 'op.night' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.faith' as const,
			'5': 'op.warehouse' as const,
			'4': 'op.connection.holy' as const,
			'19': 'op.weapon.d' as const,
			'17': 'op.heat' as const,
			eliminatedCards: [],
			'16': 'op.townhouse' as const,
			'18': 'op.licence.import' as const,
			'10': 'op.villa' as const,
		},
		mansus_peacockdoor1: {
			'1': 'ingredientgraild' as const,
			'4': 'fragmentsecrethistoriesf' as const,
			'5': 'influencegrailg' as const,
			eliminatedCards: [],
			'2': 'fascination' as const,
			'3': 'favour' as const,
		},
		mansus_peacockdoor2: {
			'2': 'fragmentsecrethistoriesf' as const,
			'3': 'influencewinterg' as const,
			'1': 'dread' as const,
			eliminatedCards: [],
		},
		'deck.send.investigate.granada': {
			'2': 'end.morbihan' as const,
			'3': 'city.marrakech' as const,
			eliminatedCards: [],
			'1': 'city.strasbourg' as const,
			'4': 'city.avignon' as const,
		},
		'deck.send.investigate.munich.turmoil': {
			'2': 'city.strasbourg' as const,
			'3': 'city.avignon' as const,
			eliminatedCards: [],
			'1': 'city.aachen' as const,
			'4': 'city.vienna' as const,
		},
		poppycommissions: {
			'1': 'commissionarticlewinterc' as const,
			'6': 'commissionarticlewinterb' as const,
			'4': 'commissionarticleknockb' as const,
			'5': 'commissionarticleknock' as const,
			eliminatedCards: [],
			'2': 'commissionarticleknockc' as const,
			'3': 'commissionarticlewinter' as const,
		},
		'deck.scout.munich': {
			'8': 'op.warehouse' as const,
			'9': 'op.horned' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.weapon.b' as const,
			'6': 'op.night' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.connection.radicals' as const,
			'5': 'op.dawn' as const,
			'4': 'loc.shrine.colonel.munich' as const,
			eliminatedCards: [],
			'10': 'op.licence.medical' as const,
		},
		'deck.explorevaultlandbeyondforest1_success': {
			'2': 'ingredientlanternf' as const,
			'3': 'theskythesoularamaic' as const,
			eliminatedCards: [],
			'1': 'influencelanternc' as const,
			'4': 'accountkanishkspidersdooraramaic' as const,
		},
		'deck.travel.wilderness.leave': {
			'1': 'city.valletta' as const,
			'37': 'city.kiev' as const,
			'35': 'city.strasbourg' as const,
			'8': 'city.vienna' as const,
			'9': 'city.meshad' as const,
			'28': 'city.avignon' as const,
			'2': 'city.sverdlovsk' as const,
			'3': 'city.london' as const,
			'18': 'city.kaunas' as const,
			'6': 'city.tirana' as const,
			'7': 'city.prague' as const,
			'4': 'city.cluj' as const,
			'5': 'city.samarkand' as const,
			'36': 'city.nizhny' as const,
			'38': 'city.granada' as const,
			'24': 'end.cheko' as const,
			'34': 'city.amsterdam' as const,
			'25': 'city.tripoli' as const,
			'14': 'city.marrakech' as const,
			'15': 'city.venice' as const,
			'40': 'end.morbihan' as const,
			'20': 'city.tiflis' as const,
			'30': 'city.alexandria' as const,
			'21': 'city.budapest' as const,
			'10': 'city.istanbul' as const,
			'26': 'city.candia' as const,
			'11': 'end.ghardaia' as const,
			'27': 'city.stalingrad' as const,
			'16': 'city.rostock' as const,
			eliminatedCards: [],
			'17': 'end.paro' as const,
			'33': 'city.aachen' as const,
			'22': 'city.algiers' as const,
			'32': 'end.bornholm' as const,
			'23': 'city.munich' as const,
			'12': 'city.baghdad' as const,
			'13': 'end.messana' as const,
			'31': 'end.slettnes' as const,
			'29': 'city.krakow' as const,
			'39': 'city.leningrad' as const,
			'19': 'city.paris' as const,
		},
		streetsstrangefinds: {
			'1': 'glimmering' as const,
			'6': 'influenceknockc' as const,
			'7': 'glimmering' as const,
			'4': 'contentment' as const,
			'5': 'fascination' as const,
			eliminatedCards: [],
			'2': 'contentment' as const,
			'3': 'influenceknockc' as const,
		},
		paintingresults: {
			'8': 'glimmering' as const,
			'9': 'mystique' as const,
			'11': 'glimmering' as const,
			'2': 'glimmering' as const,
			'3': 'glimmering' as const,
			'1': 'mystique' as const,
			'6': 'mystique' as const,
			'7': 'contentment' as const,
			'12': 'contentment' as const,
			'5': 'mystique' as const,
			'4': 'mystique' as const,
			eliminatedCards: [],
			'10': 'contentment' as const,
		},
		'deck.send.investigate.venice': {
			'2': 'city.avignon' as const,
			'3': 'city.valletta' as const,
			eliminatedCards: [],
			'1': 'city.vienna' as const,
			'4': 'city.budapest' as const,
		},
		'deck.explore.fleeting': {
			'8': 'dread' as const,
			'9': 'contentment' as const,
			'11': 'restlessness' as const,
			'2': 'contentment' as const,
			'3': 'dread' as const,
			'1': 'restlessness' as const,
			'6': 'dread' as const,
			'7': 'restlessness' as const,
			'12': 'fascination' as const,
			'5': 'fascination' as const,
			'4': 'fascination' as const,
			eliminatedCards: [],
			'10': 'contentment' as const,
		},
		'deck.explorevaultrendingmountains1_success': {
			'1': 'ingredientforgeb' as const,
			'6': 'ingredientedgef' as const,
			'7': 'bookofdissolutionmandaic' as const,
			'4': 'ingredientforgeb' as const,
			'5': 'ingredientforgeb' as const,
			'8': 'ingredientedgef' as const,
			'9': 'ingredientedgef' as const,
			eliminatedCards: [],
			'2': 'textbookmandaicaramaic' as const,
			'3': 'toolforged' as const,
		},
		'deck.scout.bornholm': {
			'2': 'obscurity' as const,
			'3': 'op.sea' as const,
			eliminatedCards: [],
			'1': 'op.cold' as const,
			'4': 'op.flowermaker' as const,
		},
		'rkx.events': {
			'2': 'rkx.event.passive' as const,
			'3': 'rkx.event.aggressive' as const,
			eliminatedCards: [],
			'1': 'rkx.event.aggressive' as const,
			'4': 'rkx.event.aggressive' as const,
		},
		mansus_spiderdoor2: {
			'1': 'influencewintere' as const,
			'6': 'influencelanterne' as const,
			'4': 'fragmentsecrethistoriesc' as const,
			'5': 'influencemothe' as const,
			eliminatedCards: [],
			'2': 'fascination' as const,
			'3': 'influenceknockg' as const,
		},
		ecdysisrewards: {
			'13': 'funds' as const,
			'14': 'compensationc' as const,
			'8': 'funds' as const,
			'9': 'kitlingripe' as const,
			'11': 'compensationb' as const,
			'2': 'vienneseconundra' as const,
			'3': 'funds' as const,
			'15': 'funds' as const,
			'1': 'jumble' as const,
			'6': 'raptintheking' as const,
			'7': 'funds' as const,
			'12': 'compensationb' as const,
			'5': 'compensationb' as const,
			'4': 'compensationb' as const,
			'19': 'funds' as const,
			'17': 'funds' as const,
			eliminatedCards: [],
			'16': 'compensationc' as const,
			'18': 'funds' as const,
			'10': 'jumble' as const,
		},
		'deck.explorevaultshires2_success': {
			'2': 'toolknockb' as const,
			'3': 'ingredientgrailb' as const,
			eliminatedCards: [],
			'1': 'toolmothb' as const,
			'4': 'flayedtantrasanskrit' as const,
		},
		schemeevents: {
			'1': 'schemeactivities' as const,
			'6': 'schemeexpedition' as const,
			'7': 'schemeexpedition' as const,
			'4': 'schemeactivities' as const,
			'5': 'schemeactivities' as const,
			eliminatedCards: [],
			'8': 'schememurder' as const,
			'9': 'schemeexpedition' as const,
			'10': 'schememurder' as const,
			'2': 'schemeactivities' as const,
			'3': 'schemeexpedition' as const,
		},
		'deck.scout.rostock': {
			'13': 'op.weapon.b' as const,
			'14': 'op.townhouse' as const,
			'8': 'op.rarity.moth' as const,
			'9': 'op.connection.official' as const,
			'11': 'op.sea' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.licence.import' as const,
			'15': 'op.office' as const,
			'1': 'op.sea' as const,
			'6': 'op.dawn' as const,
			'7': 'op.night' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.connection.underworld' as const,
			'4': 'op.cold' as const,
			eliminatedCards: [],
			'10': 'op.villa' as const,
		},
		'deck.scout.kaunas': {
			'13': 'op.licence.medical' as const,
			'14': 'op.cold' as const,
			'8': 'op.office' as const,
			'9': 'op.connection.official' as const,
			'11': 'op.wolf' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.warehouse' as const,
			'15': 'op.curio.forge' as const,
			'1': 'op.connection.ruler' as const,
			'6': 'op.dawn' as const,
			'7': 'op.night' as const,
			'12': 'op.villa' as const,
			'5': 'op.connection.underworld' as const,
			'4': 'op.connection.holy' as const,
			eliminatedCards: [],
			'16': 'op.townhouse' as const,
			'10': 'op.faith' as const,
		},
		'deck.explorevaultcontinent5_success': {
			'2': 'matthiasamethysttransformationaramaic' as const,
			'3': 'deedsofthescarredcaptaingreek' as const,
			eliminatedCards: [],
			'1': 'devouredtantrasanskrit' as const,
			'4': 'worlddoesnotweeparamaic' as const,
		},
		vaultrewardse: {
			'13': 'larquebinecodexphrygian' as const,
			'14': 'ingredientforged' as const,
			'8': 'dreamconspiracyskiesphrygian' as const,
			'9': 'tooledgef' as const,
			'21': 'toollanternfcracked' as const,
			'11': 'secondglorymandaic' as const,
			'2': 'ingredientwinterd' as const,
			'3': 'wherehasshegonevak' as const,
			'15': 'textbookvaksanskrit' as const,
			'1': 'ingredientknockd' as const,
			'6': 'bookofmasksphrygian' as const,
			'7': 'ingredientmothd' as const,
			'12': 'toolforged' as const,
			'5': 'ingredientgraild' as const,
			'23': 'textbookphrygiangreek' as const,
			'4': 'asthesunhiscoursearamaic' as const,
			'19': 'toolknockd' as const,
			'17': 'textbookmandaicaramaic' as const,
			eliminatedCards: [],
			'16': 'ingredientheartd' as const,
			'20': 'ingredientedged' as const,
			'18': 'toolgraild' as const,
			'10': 'ingredientlanternd' as const,
			'22': 'bookofdissolutionmandaic' as const,
		},
		'long.strategies.preference.intrigue': {
			'1': 'strategy.intrigue.concealed' as const,
			'4': 'strategy.intrigue.concealed' as const,
			'5': 'strategy.assault.concealed' as const,
			eliminatedCards: [],
			'2': 'strategy.downtime.concealed' as const,
			'3': 'strategy.dreams.concealed' as const,
		},
		vaultrewardsg: {
			'13': 'toolgrailf' as const,
			'14': 'bookwhitecatphrygian' as const,
			'8': 'timedivisionmandaic' as const,
			'9': 'manualdeparturevak' as const,
			'21': 'ingredientedgef' as const,
			'11': 'ingredientlanternf' as const,
			'2': 'ingredientwinterf' as const,
			'3': 'bighufffucine' as const,
			'15': 'ingredientforgef' as const,
			'1': 'ingredientknockf' as const,
			'6': 'toolknockf' as const,
			'7': 'ingredientmothf' as const,
			'12': 'scarskyfucine' as const,
			'5': 'ingredientgrailf' as const,
			'23': 'fivecreationsvak' as const,
			'4': 'toollanternf' as const,
			'19': 'originsofhoursvak' as const,
			'17': 'ingredientheartf' as const,
			eliminatedCards: [],
			'16': 'ingredientheartf' as const,
			'20': 'ingredientgrailf' as const,
			'18': 'commandspreservationallexistsmandaic' as const,
			'10': 'toolforgef' as const,
			'22': 'bookextinguishedheartmandaic' as const,
			'24': 'birdsongphrygian' as const,
		},
		vaultrewardsf: {
			'1': 'ingredientknockf' as const,
			'8': 'ingredientmothf' as const,
			'9': 'memoryofgodsfucine' as const,
			'28': 'medusaslamentgreek' as const,
			'2': 'ingredientwinterf' as const,
			'3': 'influencewintere' as const,
			'18': 'voyagesfofucine' as const,
			'6': 'ingredientgrailf' as const,
			'7': 'ingredientgraild' as const,
			'4': 'ingredientmothf' as const,
			'5': 'ingredientlanternd' as const,
			'24': 'manneralchemistsparedvak' as const,
			'25': 'ingredientwinterf' as const,
			'14': 'ingredientknockd' as const,
			'15': 'songscarapacecrossmandaic' as const,
			'20': 'toolwinterf' as const,
			'30': 'ingredientedged' as const,
			'21': 'ingredientheartf' as const,
			'10': 'toolheartf' as const,
			'26': 'toollanternd' as const,
			'11': 'toolsecrethistoriesd' as const,
			'27': 'ingredientheartd' as const,
			'16': 'ingredientforged' as const,
			eliminatedCards: [],
			'17': 'ingredientforgef' as const,
			'33': 'ingredientmothd' as const,
			'22': 'toolmothf' as const,
			'32': 'ingredientknockf' as const,
			'23': 'ingredientwinterd' as const,
			'12': 'toolknockd' as const,
			'13': 'ingredientlanternf' as const,
			'31': 'sevenfoldslayingsevencoiledfucine' as const,
			'29': 'ingredientedgef' as const,
			'19': 'focusambermandaic' as const,
		},
		vaultrewardsa: {
			'1': 'ingredientknockb' as const,
			'8': 'ingredientmothb' as const,
			'9': 'apolloandmarsyas' as const,
			'28': 'treatiseonunderplaces' as const,
			'2': 'ingredientwinterb' as const,
			'3': 'ingredientgrailb' as const,
			'18': 'textbookfucine' as const,
			'6': 'ingredientgrailb' as const,
			'7': 'roseofhypatiagreek' as const,
			'4': 'locksmithsdream4' as const,
			'5': 'chioneatabydos' as const,
			'24': 'roseofnurielgreek' as const,
			'25': 'ingredientedgeb' as const,
			'14': 'roseofwazneigreek' as const,
			'15': 'toolwinterd' as const,
			'20': 'ingredientheartb' as const,
			'21': 'travellingatnight3' as const,
			'10': 'ingredientlanternb' as const,
			'26': 'ingredientheartb' as const,
			'11': 'wainscothistories' as const,
			'27': 'toollanternbcracked' as const,
			'16': 'locksmithsdream3' as const,
			eliminatedCards: [],
			'17': 'ingredientforgeb' as const,
			'22': 'textbookgreek' as const,
			'23': 'toolheartb' as const,
			'12': 'franklinbancroftdiarieslatin' as const,
			'13': 'ingredientlanternb' as const,
			'29': 'debellismurorum' as const,
			'19': 'toolgrailb' as const,
		},
		vaultrewardsc: {
			'1': 'highmysterieschurchsolarfucine' as const,
			'37': 'ingredientheartb' as const,
			'35': 'deedsofthescarredcaptaingreek' as const,
			'8': 'ingredientgrailb' as const,
			'9': 'ingredientmothd' as const,
			eliminatedCards: [],
			'28': 'serenityofblackwoodgreek' as const,
			'2': 'ingredientknockd' as const,
			'3': 'ingredientwinterd' as const,
			'18': 'ingredientlanternd' as const,
			'6': 'ingredientlanternb' as const,
			'7': 'ingredientgraild' as const,
			'4': 'matthiasamethysttransformationaramaic' as const,
			'5': 'vinzantinscriptionsphrygian' as const,
			'36': 'toolgrailmoth' as const,
			'38': 'againstsisterhoodknotgreek' as const,
			'24': 'ingredientforged' as const,
			'34': 'toolsecrethistoriesb' as const,
			'25': 'influencemothc' as const,
			'14': 'jumble' as const,
			'15': 'tantrawormssanskrit' as const,
			'44': 'geminiadfucine' as const,
			'45': 'ingredientmothb' as const,
			'40': 'inthemountainsasupontheplainvak' as const,
			'20': 'ingredientknockb' as const,
			'30': 'toolforgeb' as const,
			'21': 'dehoris2latin' as const,
			'10': 'textbookfucinelatin' as const,
			'26': 'toolmothd' as const,
			'11': 'morphycodexaramaic' as const,
			'27': 'ingredientwinterb' as const,
			'16': 'onthematterandthedeedsofserpentsvak' as const,
			'41': 'ingredientedged' as const,
			'17': 'irreproachabletraditionssocietynobleendeavourlatin' as const,
			'46': 'ingredientmothd' as const,
			'33': 'ingredientwinterb' as const,
			'22': 'devouredtantrasanskrit' as const,
			'32': 'watchfultantrasanskrit' as const,
			'23': 'ingredientforgeb' as const,
			'12': 'textbookaramaic' as const,
			'13': 'textbookaramaic' as const,
			'42': 'ingredientedgeb' as const,
			'31': 'ingredientheartd' as const,
			'43': 'worlddoesnotweeparamaic' as const,
			'29': 'thirstingtantrasanskrit' as const,
			'39': 'ingredientheartb' as const,
			'19': 'bookoftruebloodlatin' as const,
		},
		vaultrewardsb: {
			'1': 'ingredientknockb' as const,
			'8': 'ingredientmothb' as const,
			'9': 'ingredientmothb' as const,
			'28': 'flayedtantrasanskrit' as const,
			'2': 'ingredientwinterb' as const,
			'3': 'influencewinterc' as const,
			'18': 'ingredientheartd' as const,
			'6': 'ingredientgrailb' as const,
			'7': 'thosewhodonotsleepfucine' as const,
			'4': 'toolmothb' as const,
			'5': 'concursumdiariesphrygian' as const,
			'24': 'tooledged' as const,
			'25': 'ingredientedgeb' as const,
			'14': 'shavenlocktantrasanskrit' as const,
			'15': 'toolknockb' as const,
			'20': 'ingredientheartb' as const,
			'21': 'indignitiesobliviatelatin' as const,
			'10': 'ingredientgrailb' as const,
			'26': 'toollanterndcracked' as const,
			'11': 'orchidtransfigurations3latin' as const,
			'27': 'toolwinterb' as const,
			'16': 'victoryofcrowns' as const,
			eliminatedCards: [],
			'17': 'ingredientforgeb' as const,
			'22': 'textbooklatin' as const,
			'23': 'tooledgeb' as const,
			'12': 'ingredientwinterb' as const,
			'13': 'ingredientlanternb' as const,
			'29': 'matthiasamethystlossaramaic' as const,
			'19': 'bookofcentipedegreek' as const,
		},
		'deck.send.investigate.rostock': {
			'2': 'city.prague' as const,
			'3': 'city.kaunas' as const,
			eliminatedCards: [],
			'1': 'end.bornholm' as const,
			'4': 'city.amsterdam' as const,
		},
		'deck.explorevaultloneandlevelsands3_success': {
			'2': 'songscarapacecrossmandaic' as const,
			'3': 'toolheartf' as const,
			'1': 'sevenfoldslayingsevencoiledfucine' as const,
			eliminatedCards: [],
		},
		'deck.explorevaultcontinent6_success': {
			'2': 'serenityofblackwoodgreek' as const,
			'3': 'textbookfucinelatin' as const,
			eliminatedCards: [],
			'1': 'onthematterandthedeedsofserpentsvak' as const,
			'4': 'irreproachabletraditionssocietynobleendeavourlatin' as const,
		},
		'deck.explorevaulteveningisles1_success': {
			'2': 'originsofhoursvak' as const,
			'3': 'fivecreationsvak' as const,
			eliminatedCards: [],
			'1': 'manualdeparturevak' as const,
			'4': 'toolgrailf' as const,
		},
		'deck.scout.paris': {
			'13': 'op.warehouse' as const,
			'14': 'op.licence.medical' as const,
			'8': 'op.weapon.b' as const,
			'9': 'op.townhouse' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.rarity.grail' as const,
			'1': 'op.flowermaker' as const,
			'6': 'op.dawn' as const,
			'7': 'op.night' as const,
			'12': 'op.connection.underworld' as const,
			'5': 'op.connection.official' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.heights' as const,
		},
		'deck.send.investigate.london.turmoil': {
			'2': 'end.morbihan' as const,
			'3': 'city.paris' as const,
			eliminatedCards: [],
			'1': 'end.bornholm' as const,
			'4': 'city.amsterdam' as const,
		},
		'deck.send.investigate.valletta': {
			'2': 'city.algiers' as const,
			'3': 'city.tripoli' as const,
			eliminatedCards: [],
			'1': 'city.venice' as const,
			'4': 'city.tirana' as const,
		},
		'deck.send.investigate.london': {
			'2': 'end.morbihan' as const,
			'3': 'city.paris' as const,
			eliminatedCards: [],
			'1': 'end.bornholm' as const,
			'4': 'city.amsterdam' as const,
		},
		oneoffrewards: {
			'1': 'fragmentknockb' as const,
			'6': 'fragmentforgeb' as const,
			'7': 'fragmentheartb' as const,
			'4': 'fragmentmothb' as const,
			'5': 'fragmentlanternb' as const,
			'8': 'fragmentedgeb' as const,
			eliminatedCards: [],
			'2': 'fragmentwinterb' as const,
			'3': 'fragmentgrailb' as const,
		},
		'deck.explorevaultlandbeyondforest4_success': {
			'2': 'ingredientforgeb' as const,
			'3': 'howendwillbeginvak' as const,
			eliminatedCards: [],
			'1': 'furioustantrasanskrit' as const,
			'4': 'twinserpenttantrasanskrit' as const,
		},
		'deck.scout.tirana': {
			'8': 'op.townhouse' as const,
			'9': 'op.flowermaker' as const,
			'11': 'op.warehouse' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.ruler' as const,
			'6': 'op.sunset' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.licence.medical' as const,
			'5': 'op.dawn' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.send.investigate.munich': {
			'2': 'city.strasbourg' as const,
			'3': 'city.avignon' as const,
			eliminatedCards: [],
			'1': 'city.aachen' as const,
			'4': 'city.vienna' as const,
		},
		'deck.scout.stalingrad': {
			'13': 'op.licence.medical' as const,
			'8': 'loc.shrine.colonel.stalingrad' as const,
			'9': 'op.wolf' as const,
			'11': 'op.curio.moth' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.radicals' as const,
			'6': 'op.night' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.cold' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.use.connection.official': {
			'2': 'op.licence.medical' as const,
			'1': 'op.licence.import' as const,
			eliminatedCards: [],
		},
		'deck.send.investigate.kiev': {
			'2': 'city.krakow' as const,
			'3': 'city.cluj' as const,
			eliminatedCards: [],
			'1': 'city.leningrad' as const,
			'4': 'city.stalingrad' as const,
		},
		'deck.talk.ghoul.memory.joyful': {
			'1': 'influenceheartc' as const,
			'4': 'influenceheartc' as const,
			'5': 'influencehearte' as const,
			eliminatedCards: [],
			'2': 'contentment' as const,
			'3': 'contentment' as const,
		},
		'deck.scout.paro': {
			'1': 'op.faith' as const,
			'6': 'op.heights' as const,
			'4': 'obscurity' as const,
			'5': 'op.cats' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'op.cold' as const,
		},
		'deck.send.investigate.leningrad.turmoil': {
			'2': 'city.kaunas' as const,
			'3': 'city.kiev' as const,
			eliminatedCards: [],
			'1': 'end.slettnes' as const,
			'4': 'city.nizhny' as const,
		},
		'deck.send.investigate.istanbul': {
			'2': 'city.tirana' as const,
			'3': 'city.alexandria' as const,
			eliminatedCards: [],
			'1': 'city.cluj' as const,
			'4': 'city.baghdad' as const,
		},
		'rkx.weaknesses.quirk': {
			'2': 'rkx.weakness.cats.hidden' as const,
			'3': 'rkx.weakness.faith.hidden' as const,
			'1': 'rkx.weakness.heights.hidden' as const,
			eliminatedCards: [],
		},
		vaultsloneandlevelsands: {
			'2': 'vaultloneandlevelsands4' as const,
			'3': 'vaultloneandlevelsands3' as const,
			eliminatedCards: [],
			'1': 'vaultloneandlevelsands1' as const,
			'4': 'vaultloneandlevelsands2' as const,
		},
		'deck.scout.amsterdam': {
			'13': 'op.villa' as const,
			'14': 'op.warehouse' as const,
			'8': 'op.licence.import' as const,
			'9': 'op.morgen' as const,
			'11': 'op.townhouse' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.office' as const,
			'1': 'op.weapon.b' as const,
			'6': 'op.dawn' as const,
			'7': 'op.sunset' as const,
			'12': 'op.connection.underworld' as const,
			'5': 'op.connection.official' as const,
			'4': 'op.sea' as const,
			eliminatedCards: [],
			'10': 'op.sea' as const,
		},
		'long.strategies.preference.dreamwork': {
			'1': 'strategy.intrigue.concealed' as const,
			'4': 'strategy.dreams.concealed' as const,
			'5': 'strategy.assault.concealed' as const,
			eliminatedCards: [],
			'2': 'strategy.downtime.concealed' as const,
			'3': 'strategy.dreams.concealed' as const,
		},
		vaultsshires: {
			'1': 'vaultshires2' as const,
			'4': 'vaultshires3' as const,
			'5': 'vaultshires1' as const,
			eliminatedCards: [],
			'2': 'vaultshires5' as const,
			'3': 'vaultshires4' as const,
		},
		'deck.scout.granada': {
			'13': 'op.licence.medical' as const,
			'14': 'op.heat' as const,
			'8': 'op.office' as const,
			'9': 'op.connection.official' as const,
			'11': 'op.flowermaker' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.warehouse' as const,
			'15': 'op.curio.heart' as const,
			'1': 'op.night' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.dawn' as const,
			'12': 'op.villa' as const,
			'5': 'op.connection.underworld' as const,
			'4': 'op.cats' as const,
			eliminatedCards: [],
			'16': 'op.townhouse' as const,
			'10': 'op.heights' as const,
		},
		'deck.explorevaultcapital2_success': {
			'2': 'hq.mithraeum.potential' as const,
			'3': 'toollanternbcracked' as const,
			eliminatedCards: [],
			'1': 'ingredientlanternb' as const,
			'4': 'toolwinterd' as const,
		},
		'deck.scout.budapest': {
			'13': 'op.licence.medical' as const,
			'8': 'op.townhouse' as const,
			'9': 'op.medusa' as const,
			'11': 'op.curio.grail' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.underworld' as const,
			'6': 'op.night' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		vaultseveningisles: {
			'2': 'vaulteveningisles4' as const,
			'3': 'vaulteveningisles3' as const,
			eliminatedCards: [],
			'1': 'vaulteveningisles1' as const,
			'4': 'vaulteveningisles2' as const,
		},
		'deck.send.investigate.stalingrad': {
			'2': 'city.kiev' as const,
			'3': 'city.tiflis' as const,
			eliminatedCards: [],
			'1': 'city.nizhny' as const,
			'4': 'city.sverdlovsk' as const,
		},
		randominfluencelow: {
			'48': 'influenceforgec' as const,
			'1': 'influenceknock' as const,
			'49': 'influenceedgec' as const,
			'37': 'influenceheart' as const,
			'35': 'vitality' as const,
			'8': 'erudition' as const,
			'9': 'influencelantern' as const,
			eliminatedCards: [],
			'28': 'influenceforgec' as const,
			'2': 'influenceknockc' as const,
			'3': 'vitality' as const,
			'18': 'influenceheart' as const,
			'6': 'glimmering' as const,
			'7': 'influencemoth' as const,
			'4': 'influencewinterc' as const,
			'5': 'influenceknockc' as const,
			'36': 'influencegrailc' as const,
			'38': 'influenceheartc' as const,
			'51': 'influenceforge' as const,
			'56': 'influencemoth' as const,
			'24': 'influencelanternc' as const,
			'34': 'influencewinterc' as const,
			'25': 'influencelantern' as const,
			'14': 'influencemothc' as const,
			'15': 'influencemoth' as const,
			'44': 'influencegrail' as const,
			'54': 'influencegrailc' as const,
			'45': 'influenceheartc' as const,
			'55': 'influencewinter' as const,
			'40': 'influencelantern' as const,
			'20': 'erudition' as const,
			'30': 'influenceforgec' as const,
			'21': 'influencelanternc' as const,
			'10': 'influencegrailc' as const,
			'26': 'influenceknock' as const,
			'11': 'influenceforge' as const,
			'27': 'influenceheartc' as const,
			'16': 'influenceedgec' as const,
			'41': 'influencewinter' as const,
			'17': 'influencelanternc' as const,
			'46': 'influencewinterc' as const,
			'52': 'influenceedgec' as const,
			'47': 'vitality' as const,
			'57': 'influencemothc' as const,
			'33': 'influencegrail' as const,
			'22': 'influencewinter' as const,
			'32': 'influenceedge' as const,
			'23': 'influenceedge' as const,
			'12': 'influencegrail' as const,
			'13': 'influencemothc' as const,
			'42': 'erudition' as const,
			'31': 'influenceknock' as const,
			'43': 'glimmering' as const,
			'53': 'influenceedge' as const,
			'50': 'influenceheart' as const,
			'29': 'influenceforge' as const,
			'39': 'glimmering' as const,
			'19': 'influenceknockc' as const,
		},
		'deck.scout.prague': {
			'13': 'op.licence.medical' as const,
			'8': 'op.townhouse' as const,
			'9': 'op.cold' as const,
			'11': 'op.curio.knock' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.connection.ruler' as const,
			'6': 'op.night' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.scout.valletta': {
			'13': 'op.licence.import' as const,
			'8': 'op.townhouse' as const,
			'9': 'loc.shrine.colonel.valletta' as const,
			'11': 'op.curio.forge' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.underworld' as const,
			'1': 'op.sea' as const,
			'6': 'op.sea' as const,
			'7': 'op.connection.official' as const,
			'12': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			'4': 'op.villa' as const,
			eliminatedCards: [],
			'10': 'op.office' as const,
		},
		'deck.explorevaultcapital3_success': {
			'1': 'ingredientgrailb' as const,
			'4': 'franklinbancroftdiarieslatin' as const,
			'5': 'toolheartb' as const,
			eliminatedCards: [],
			'2': 'hq.warehouse.potential' as const,
			'3': 'apolloandmarsyas' as const,
		},
		'deck.scout.aachen': {
			'1': 'op.weapon.a' as const,
			'6': 'op.weapon.b' as const,
			'7': 'op.warehouse' as const,
			'4': 'loc.shrine.colonel.aachen' as const,
			'5': 'op.night' as const,
			eliminatedCards: [],
			'8': 'op.connection.radicals' as const,
			'9': 'op.licence.medical' as const,
			'11': 'op.connection.underworld' as const,
			'10': 'op.office' as const,
			'2': 'op.dawn' as const,
			'3': 'op.connection.official' as const,
		},
		'deck.scout.kiev': {
			'13': 'op.warehouse' as const,
			'14': 'op.licence.medical' as const,
			'8': 'op.connection.underworld' as const,
			'9': 'op.marinette' as const,
			'11': 'op.office' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.radicals' as const,
			'1': 'op.connection.holy' as const,
			'6': 'op.dawn' as const,
			'7': 'op.sunset' as const,
			'12': 'op.connection.official' as const,
			'5': 'op.curio.knock' as const,
			'4': 'op.heights' as const,
			eliminatedCards: [],
			'10': 'op.faith' as const,
		},
		'deck.explorevaultshires1_success': {
			'2': 'ingredientheartd' as const,
			'3': 'orchidtransfigurations3latin' as const,
			'1': 'indignitiesobliviatelatin' as const,
			eliminatedCards: [],
		},
		citysecrets: {
			'2': 'locationstreetsstrange' as const,
			'3': 'locationbookdealer' as const,
			eliminatedCards: [],
			'1': 'locationauctionhouse' as const,
			'4': 'locationcabaret' as const,
		},
		'deck.explorevaultrendingmountains2_success': {
			'1': 'wherehasshegonevak' as const,
			'4': 'tooledgef' as const,
			'5': 'toolgraild' as const,
			eliminatedCards: [],
			'2': 'textbookvaksanskrit' as const,
			'3': 'dreamconspiracyskiesphrygian' as const,
		},
		'deck.explorevaultfloating1_success': {
			'2': 'firecircletantrasanskrit' as const,
			'3': 'incandescenttantrasanskrit' as const,
			eliminatedCards: [],
			'1': 'ceaselesstantrasanskrit' as const,
			'4': 'leoninetantrasanskrit' as const,
		},
		'deck.explorevaultshires4_success': {
			'2': 'victoryofcrowns' as const,
			'3': 'toollanterndcracked' as const,
			'1': 'tooledged' as const,
			eliminatedCards: [],
		},
		'deck.scout.sverdlovsk': {
			'1': 'op.connection.radicals' as const,
			'6': 'op.night' as const,
			'7': 'op.office' as const,
			'4': 'op.warehouse' as const,
			'5': 'op.dawn' as const,
			eliminatedCards: [],
			'8': 'op.cold' as const,
			'9': 'op.connection.underworld' as const,
			'11': 'op.connection.official' as const,
			'10': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.curio.heart' as const,
		},
		robberyrewards: {
			'1': 'funds' as const,
			'37': 'compensation' as const,
			'35': 'funds' as const,
			'8': 'compensation' as const,
			'9': 'ingredientknockb' as const,
			eliminatedCards: [],
			'28': 'funds' as const,
			'2': 'ingredientgrailb' as const,
			'3': 'ingredientmothb' as const,
			'18': 'ingredientheartb' as const,
			'6': 'compensation' as const,
			'7': 'ingredientedgeb' as const,
			'4': 'jumble' as const,
			'5': 'funds' as const,
			'36': 'funds' as const,
			'38': 'funds' as const,
			'24': 'compensationb' as const,
			'34': 'funds' as const,
			'25': 'funds' as const,
			'14': 'funds' as const,
			'15': 'funds' as const,
			'44': 'funds' as const,
			'40': 'jumble' as const,
			'20': 'compensation' as const,
			'30': 'funds' as const,
			'21': 'funds' as const,
			'10': 'jumble' as const,
			'26': 'funds' as const,
			'11': 'funds' as const,
			'27': 'jumble' as const,
			'16': 'jumble' as const,
			'41': 'funds' as const,
			'17': 'funds' as const,
			'33': 'funds' as const,
			'22': 'funds' as const,
			'32': 'funds' as const,
			'23': 'compensation' as const,
			'12': 'funds' as const,
			'13': 'funds' as const,
			'42': 'funds' as const,
			'31': 'compensationb' as const,
			'43': 'compensation' as const,
			'29': 'ingredientforgeb' as const,
			'39': 'compensationb' as const,
			'19': 'funds' as const,
		},
		'deck.use.first': {
			'1': 'city.krakow' as const,
			'6': 'city.prague' as const,
			'7': 'city.london' as const,
			'4': 'city.venice' as const,
			'5': 'city.avignon' as const,
			'8': 'city.aachen' as const,
			eliminatedCards: [],
			'2': 'city.budapest' as const,
			'3': 'city.munich' as const,
		},
		'deck.send.investigate.kiev.turmoil': {
			'2': 'city.krakow' as const,
			'3': 'city.cluj' as const,
			eliminatedCards: [],
			'1': 'city.leningrad' as const,
			'4': 'city.stalingrad' as const,
		},
		'deck.send.investigate.candia': {
			'2': 'city.tripoli' as const,
			'3': 'end.messana' as const,
			eliminatedCards: [],
			'1': 'city.tirana' as const,
			'4': 'city.alexandria' as const,
		},
		'deck.scout.tiflis': {
			'8': 'op.office' as const,
			'9': 'op.heights' as const,
			'11': 'op.licence.medical' as const,
			'2': 'op.weapon.a' as const,
			'3': 'op.connection.official' as const,
			'1': 'op.wolf' as const,
			'6': 'op.weapon.b' as const,
			'7': 'op.curio.lantern2' as const,
			'12': 'op.connection.underworld' as const,
			'5': 'op.dawn' as const,
			'4': 'op.warehouse' as const,
			eliminatedCards: [],
			'10': 'op.connection.radicals' as const,
		},
		mansus_stagdoor1: {
			'2': 'influencegrailc' as const,
			'3': 'influenceedgee' as const,
			'1': 'influencewintere' as const,
			eliminatedCards: [],
		},
		'deck.explorevaultcapital5_success': {
			'1': 'chioneatabydos' as const,
			'6': 'roseofwazneigreek' as const,
			'4': 'textbookgreek' as const,
			'5': 'debellismurorum' as const,
			eliminatedCards: [],
			'2': 'hq.church.potential' as const,
			'3': 'roseofnurielgreek' as const,
		},
		graillong: {
			'2': 'tryphon_unknown' as const,
			'3': 'tryphon_unknown' as const,
			'1': 'julian_unknown' as const,
			eliminatedCards: [],
		},
		randomvictim: {
			'2': 'genericprisonerm' as const,
			'1': 'genericprisonerf' as const,
			eliminatedCards: [],
		},
		mansus_wood: {
			'2': 'fragmentsecrethistories' as const,
			'3': 'influencemoth' as const,
			'1': 'rumour' as const,
			eliminatedCards: [],
		},
		'deck.scout.tripoli': {
			'13': 'op.licence.import' as const,
			'14': 'op.heat' as const,
			'8': 'op.office' as const,
			'9': 'op.connection.official' as const,
			'11': 'op.sea' as const,
			'2': 'op.weapon.d' as const,
			'3': 'op.warehouse' as const,
			'15': 'op.curio.lantern3' as const,
			'1': 'op.sunset' as const,
			'6': 'op.weapon.a' as const,
			'7': 'op.dawn' as const,
			'12': 'op.villa' as const,
			'5': 'op.connection.underworld' as const,
			'4': 'op.sea' as const,
			eliminatedCards: [],
			'16': 'op.townhouse' as const,
			'10': 'op.cats' as const,
		},
		'deck.send.investigate.tiflis': {
			'2': 'city.cluj' as const,
			'3': 'city.baghdad' as const,
			eliminatedCards: [],
			'1': 'city.stalingrad' as const,
			'4': 'city.samarkand' as const,
		},
		scholarpatrons: {
			'1': 'bechetready' as const,
			'4': 'janningsready' as const,
			'5': 'aladimready' as const,
			eliminatedCards: [],
			'2': 'sulochana' as const,
			'3': 'poppyready' as const,
		},
		mansus_stagdoor2: {
			'2': 'fragmentsecrethistoriesd' as const,
			'3': 'fascination' as const,
			'1': 'eruditionplus' as const,
			eliminatedCards: [],
		},
		dreamreasonresults: {
			'1': 'glimmering' as const,
			'4': 'contentment' as const,
			'5': 'vitality' as const,
			eliminatedCards: [],
			'2': 'restlessness' as const,
			'3': 'dread' as const,
		},
		talkevents: {
			'1': 'dayacquaintances' as const,
			'6': 'dayacquaintances' as const,
			'7': 'dayacquaintances' as const,
			'4': 'daypatrons' as const,
			'5': 'dayacquaintances' as const,
			'8': 'dayacquaintances' as const,
			'9': 'dayacquaintances' as const,
			eliminatedCards: [],
			'2': 'daypatrons' as const,
			'3': 'dayacquaintances' as const,
		},
		'deck.send.investigate.tirana': {
			'2': 'city.valletta' as const,
			'3': 'city.candia' as const,
			eliminatedCards: [],
			'1': 'city.budapest' as const,
			'4': 'city.istanbul' as const,
		},
		'deck.scout.ghardaia': {
			'1': 'op.cats' as const,
			'4': 'op.flowermaker' as const,
			'5': 'op.heat' as const,
			eliminatedCards: [],
			'2': 'op.dawn' as const,
			'3': 'obscurity' as const,
		},
		'rkx.weaknesses.environment': {
			'2': 'rkx.weakness.heat.hidden' as const,
			'3': 'rkx.weakness.cold.hidden' as const,
			'1': 'rkx.weakness.sea.hidden' as const,
			eliminatedCards: [],
		},
		'deck.scout.wilderness': {
			'2': 'op.heat' as const,
			'3': 'op.cold' as const,
			'1': 'op.sea' as const,
			eliminatedCards: [],
		},
		'deck.send.investigate.tripoli': {
			'2': 'city.algiers' as const,
			'3': 'end.ghardaia' as const,
			eliminatedCards: [],
			'1': 'city.valletta' as const,
			'4': 'city.candia' as const,
		},
		vaultrewardsd: {
			'1': 'ingredientknockd' as const,
			'37': 'twinserpenttantrasanskrit' as const,
			'35': 'ingredientedgeb' as const,
			'8': 'ingredientmothd' as const,
			'9': 'silverbookfucine' as const,
			'28': 'historyofshadowlesskingsaramaic' as const,
			'2': 'ingredientwinterd' as const,
			'3': 'knownunknowntantrasanskrit' as const,
			'18': 'ingredientforgeb' as const,
			'6': 'ingredientgraild' as const,
			'7': 'ingredientgrailb' as const,
			'4': 'furioustantrasanskrit' as const,
			'5': 'ingredientlanternb' as const,
			'36': 'burningwomanphrygian' as const,
			'38': 'ingredientmothb' as const,
			'24': 'theskythesoularamaic' as const,
			'34': 'ingredientedged' as const,
			'25': 'ingredientheartd' as const,
			'14': 'ironbookfucine' as const,
			'15': 'ingredientlanternd' as const,
			'20': 'ingredientforged' as const,
			'30': 'twentysixenticementsseventormentsfucine' as const,
			'21': 'ingredientgrailf' as const,
			'10': 'howendwillbeginvak' as const,
			'26': 'textbooksanskrit' as const,
			'11': 'catalogueofunchartedpleasuresphrygian' as const,
			'27': 'ingredientwinterb' as const,
			'16': 'ingredientknockb' as const,
			eliminatedCards: [],
			'17': 'ingredientlanternf' as const,
			'33': 'sunsetpassageslatin' as const,
			'22': 'toolheartd' as const,
			'32': 'ingredientheartb' as const,
			'23': 'matthiasamethystpursuitaramaic' as const,
			'12': 'ivorybookfucine' as const,
			'13': 'gospelzacchaeusgreek' as const,
			'31': 'accountkanishkspidersdooraramaic' as const,
			'29': 'encirclingtantrasanskrit' as const,
			'39': 'bookofthronesphrygian' as const,
			'19': 'ingredientforgeb' as const,
		},
		auctionedcommontomes: {
			'1': 'textbooksanskrit' as const,
			'8': 'textbookreason' as const,
			'9': 'waroftheroadscensored' as const,
			'2': 'textbookpassion' as const,
			'3': 'introductiontohistories' as const,
			'18': 'textbookgreek' as const,
			'6': 'textbooklatin' as const,
			'7': 'victoryofcrowns' as const,
			'4': 'travellingatnight1' as const,
			'5': 'onwhatiscontainedbysilvergreek' as const,
			'24': 'skeletonsongs' as const,
			'25': 'locksmithsdream2' as const,
			'14': 'locksmithsdream1' as const,
			'15': 'burningofunburntgod' as const,
			'20': 'orchidtransfigurations2latin' as const,
			'21': 'humoursofagentleman' as const,
			'10': 'sixlettersonnecessity' as const,
			'26': 'travellingatnight2' as const,
			'11': 'onthewhite' as const,
			'27': 'orchidtransfigurations1latin' as const,
			'16': 'apolloandmarsyas' as const,
			eliminatedCards: [],
			'17': 'queensoftherivers' as const,
			'22': 'stumm' as const,
			'23': 'truecompleteasclepiangreek' as const,
			'12': 'textbookpassion' as const,
			'13': 'debellismurorumlatin' as const,
			'19': 'dehoris1latin' as const,
		},
		'deck.send.investigate.cluj': {
			'2': 'city.budapest' as const,
			'3': 'city.istanbul' as const,
			eliminatedCards: [],
			'1': 'city.kiev' as const,
			'4': 'city.tiflis' as const,
		},
		mansus_whitedoor: {
			'2': 'fragmentsecrethistoriesb' as const,
			'3': 'influencewinterc' as const,
			'1': 'restlessness' as const,
			eliminatedCards: [],
		},
	},
	metainfo: {
		VERSIONNUMBER: '2021.1.b.2' as const,
	},
	characterDetails: {
		executions: {
			despairdefeated: '8' as const,
			paintingreputationcheck: '24' as const,
			workhealth: '16' as const,
			dreamstartingpassion: '1' as const,
			recoverillhealthfundsvitality: '11' as const,
			suspicioncreatefirsthunter: '1' as const,
			despairrisk: '8' as const,
			paintwithskill: '1' as const,
			paintingqualityexceptional: '12' as const,
			studyincreasepassionstarter: '1' as const,
			studyreason: '12' as const,
			workhealth_noinjurychance: '3' as const,
			studyincreasevitalitytoplus: '5' as const,
			despairrisklink: '8' as const,
			paintluck: '11' as const,
			visionsrisk: '11' as const,
			studyincreasehealthskilla: '1' as const,
			painthasfunds: '5' as const,
			despairactive: '1' as const,
			painthasinfluence: '23' as const,
			paintingreputation_known: '5' as const,
			L_continuerose_noone: '5' as const,
			paintthreepassion: '3' as const,
			workhealthskillc: '1' as const,
			paintaddpigment: '15' as const,
			L_roserouter: '5' as const,
			suspiciontrycreatehunter: '4' as const,
			introdream: '1' as const,
			studypassion: '7' as const,
			painttwopassion: '17' as const,
			studyincreasepassionskilla: '1' as const,
			paintingqualitycompetent: '1' as const,
			paintingreputation_noticed: '2' as const,
			studyincreaseglimmeringtoplus: '5' as const,
			paintbasicsuccess: '2' as const,
			studyincreasepassionskillb: '1' as const,
			drawseason: '60' as const,
			'painting.reputation.overexposure': '11' as const,
			lanterninduction: '1' as const,
			paintingreputation_unknown: '1' as const,
			reducefascinationfleeting: '1' as const,
			needs: '60' as const,
			studyincreasereasonskillb: '1' as const,
			bequestcountdown: '1' as const,
			suspicion: '10' as const,
			sickness: '6' as const,
			paintonepassion: '3' as const,
			ascensionnotyet: '12' as const,
			dream_router: '1' as const,
			studyincreaseeruditiontoplus: '5' as const,
			paintingreputation_significant: '14' as const,
			discardseason: '60' as const,
			studyincreasereasonstarter: '1' as const,
			heartinduction: '2' as const,
			studyincreasehealthskillb: '1' as const,
			paintingqualitygood: '11' as const,
			reducedread: '3' as const,
			ambition: '12' as const,
			paintnopassion: '1' as const,
			paintresults: '24' as const,
			studyhealth: '11' as const,
			workhealthinjury: '6' as const,
			despairabate: '1' as const,
			visionsdefeated: '11' as const,
			rosenext: '5' as const,
			visionsrisklink: '11' as const,
			paintingreputation_notable: '2' as const,
			studyincreasereasonskilla: '1' as const,
			recoverfatigue: '11' as const,
			workintrojob: '1' as const,
			bequestarrives: '1' as const,
			nightmarecleansingdawn: '1' as const,
			studyincreasehealthstarter: '1' as const,
		},
		name: 'Thomas' as const,
		profession: 'The Aspirant' as const,
		pastLevers: {
			lastheadquarters: 'generichq' as const,
			lastfollower: 'rose_b' as const,
			lastsignificantpainting: 'paintingmansus' as const,
			lastpersonkilled: 'neville_a' as const,
			lastcharactername: 'J.N. Sinombre' as const,
			lastcult: 'cultgrail_1' as const,
			lasttool: 'toolknockb' as const,
			lastbook: 'textbooksanskrit' as const,
			lastdesire: 'ascensionsensationa' as const,
		},
		futureLevers: {
			lastcharactername: 'Thomas' as const,
		},
		activeLegacy: 'aspirant' as const,
	},
	situations: {
		'-810_390_5765c74b-c4d6-4bf4-9a12-4d85da2f6b04': {
			situationStoredElements: {
				'slot_storage_ec44282a-03ee-4ce7-9f6d-1b72b9f06dc5': {
					lifetimeRemaining: '1' as const,
					lastTablePosX: '0' as const,
					markedForConsumption: 'False' as const,
					elementId: 'seasondespair' as const,
					lastTablePosY: '0' as const,
					quantity: '1' as const,
				},
			},
			verbId: 'time' as const,
			ongoingSlotElements: {
				'Expenses_c0ba1e54-1016-4074-b9f2-34849347942b': {
					lifetimeRemaining: '0' as const,
					lastTablePosX: '90' as const,
					markedForConsumption: 'False' as const,
					elementId: 'funds' as const,
					lastTablePosY: '-130' as const,
					quantity: '1' as const,
				},
			},
			situationWindowY: '533.1327' as const,
			title: 'Time Passes' as const,
			timeRemaining: '14.84976' as const,
			recipeId: 'needs' as const,
			situationWindowX: '-592.7335' as const,
			state: 'Ongoing' as const,
			situationOutputNotes: {
				'1': {
					title: "Time, the sundial's shadow, passes. I must have Funds to live, or I will become ill.",
				},
			},
			situationWindowOpen: 'False' as const,
			situationWindowZ: '-100' as const,
			completioncount: '0' as const,
		},
		'-540_390_5e908ec5-18b8-4ddd-82f4-dd5e7ab94249': {
			timeRemaining: '8.399929' as const,
			recipeId: 'workhealthskillc' as const,
			state: 'Ongoing' as const,
			situationWindowOpen: 'False' as const,
			situationWindowX: '-527.6758' as const,
			situationWindowZ: '-100' as const,
			situationOutputNotes: {
				'1': {
					title: 'Once again I put my strength to use.' as const,
				},
			},
			title: 'Unskilled Labour: Arms of Steel' as const,
			verbId: 'work' as const,
			situationWindowY: '583.0729' as const,
			situationStoredElements: {
				'slot_storage_c00d9752-8fca-42a2-acdb-96b2b7fc2a33': {
					lifetimeRemaining: '0' as const,
					lastTablePosX: '270' as const,
					markedForConsumption: 'False' as const,
					elementId: 'health' as const,
					lastTablePosY: '650' as const,
					quantity: '1' as const,
				},
				'slot_storage_889dc3e3-63db-46b1-925d-539d7a8a3683': {
					lifetimeRemaining: '0' as const,
					lastTablePosX: '180' as const,
					markedForConsumption: 'False' as const,
					elementId: 'skillhealthc' as const,
					lastTablePosY: '650' as const,
					quantity: '1' as const,
				},
			},
			completioncount: '0' as const,
		},
		'-270_390_1742620d-a125-42ce-931b-a055797084bb': {
			timeRemaining: '0' as const,
			recipeId: null, // originally NULL in all caps (I don't know why)
			state: 'Unstarted' as const,
			situationWindowOpen: 'False' as const,
			situationWindowX: '-257.6758' as const,
			situationWindowZ: '-100' as const,
			situationOutputNotes: {
				'1': {
					title: 'Rest; reconsider your priorities; or risk yourself in exploration of the kingdoms of sleep.' as const,
				},
			},
			title: 'Dream' as const,
			verbId: 'dream' as const,
			situationWindowY: '583.0729' as const,
			completioncount: '0' as const,
		},
		'0_390_d6650b1e-e12f-45d1-b671-edacf80f7777': {
			timeRemaining: '0' as const,
			recipeId: null, // orignally 'NULL' in all caps (idk why)
			state: 'Unstarted' as const,
			situationWindowOpen: 'False' as const,
			situationWindowX: '12.32416' as const,
			situationWindowZ: '-100' as const,
			situationOutputNotes: {
				'1': {
					title: 'Unlock books and other treasures.' as const,
				},
			},
			title: 'Study' as const,
			verbId: 'study' as const,
			situationWindowY: '583.0729' as const,
			completioncount: '0' as const,
		},
	},
};
export type SaveStateExample = typeof saveStateExample;
export default saveStateExample;
