load("//ts:rules.bzl", "jest_test")
load("//:rules.bzl", "go_library")

go_library(
    name = "flagutil",
    srcs = glob(["*.go"]),
    importpath = "github.com/zemnmez/monorepo/go/flag/flagutil",
    visibility = ["//visibility:public"],
)
