load("//:rules.bzl", "go_library")


go_library(
    name = "flagutil",
    srcs = glob(["*.go"]),
    visibility = ["//visibility:public"],
    importpath = "github.com/zemnmez/quickcult/go/flag/flagutil"
)
