load("//ts:rules.bzl", "eslint_test", "jest_test", "ts_lint", "ts_project")
load("//:rules.bzl", "go_library")

go_library(
    name = "flagutil",
    srcs = glob(["*.go"]),
    importpath = "github.com/zemnmez/monorepo/go/flag/flagutil",
    visibility = ["//visibility:public"],
)
