load("//:rules.bzl", "go_library")


go_library(
    name = "ziputil",
    srcs = glob(["*.go"]),
    visibility = ["//visibility:public"],
    importpath = "github.com/zemnmez/quickcult/go/archive/zip/ziputil"
)
