load("//:rules.bzl", "go_library")

go_library(
    name = "ziputil",
    srcs = glob(["*.go"]),
    importpath = "github.com/zemnmez/monorepo/go/archive/zip/ziputil",
    visibility = ["//visibility:public"],
)
