# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---

name: Presubmit
# yamllint disable rule:line-length
#

on:   # yamllint disable-line rule:truthy
  merge_group:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited # not in the default set, will run on rebase.

env:
  BAZEL: ./sh/bin/bazel


jobs:
  # fake staging for merge-queue only check.
  # https://github.com/orgs/community/discussions/103114#discussioncomment-8359045
  Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: true
  Presubmit:
    permissions:
      contents: read
      id-token: write
    concurrency:
      # > The ref given is fully-formed, meaning that for branches the format
      # > is refs/heads/<branch_name>,
      # > for pull requests it is refs/pull/<pr_number>/merge,
      # > and for tags it is refs/tags/<tag_name>. For example,
      # > refs/heads/feature-branch-1.
      #
      # This should cancel a prior presubmit when a new change comes in.
      group: >
        ${{ github.workflow }}-
        ${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    # Performs all offline testing.
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: false
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        name: Acquire federated GCloud credentials for secrets...
        id: secret_auth
        continue-on-error: true
        with:
          project_id: 'extreme-cycling-441523-a9'
          workload_identity_provider: 'projects/845702659200/locations/global/workloadIdentityPools/github/providers/my-repo'
      - uses: 'google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262' # v3.0.0
        if: steps.secret_auth.outcome == 'success'
        name: Read CI secrets from Secret Manager
        id: secrets
        continue-on-error: true
        with:
          secrets: |-
            readonly_buildbuddy_api_key:extreme-cycling-441523-a9/github-actions-readonly-buildbuddy-api-key
      - name: Presubmit
        run: |
         ./.github/workflows/prepare_ci.sh && \
         echo "::group::Presubmit prep" && \
         $BAZEL build --config=ci --tool_tag=presubmit //ci:presubmit && \
         echo "::endgroup::" && \
         echo "::group::Presubmit" && \
         $BAZEL run --config=ci --tool_tag=presubmit //ci:presubmit -- --skip-pulumi-deploy && \
         echo "::endgroup::"
        env:
          BUILDBUDDY_API_KEY: ${{ steps.secrets.outputs.readonly_buildbuddy_api_key }}
