# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---


name: Renovate
# yamllint disable rule:line-length
concurrency:
  # if another instance of renovate is running,
  # do not attempt to run overlapping instances.
  group: renovate
on: # yamllint disable-line rule:truthy
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        name: Acquire federated GCloud credentials for secrets...
        id: secret_auth
        with:
          project_id: 'extreme-cycling-441523-a9'
          workload_identity_provider: 'projects/845702659200/locations/global/workloadIdentityPools/github/providers/my-repo'
      - uses: 'google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262' # v3.0.0
        name: Read Renovate token from Secret Manager
        id: secrets
        with:
          secrets: |-
            gh_pat:extreme-cycling-441523-a9/github-actions-gh-pat
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@6d859fc95779be83a0335ca704879b47e5d79641 # v46.1.16
        with:
          configurationFile: .github/renovate-global.json
          renovate-version: ${{ env.RENOVATE_VERSION }}
          token: ${{ steps.secrets.outputs.gh_pat }}
    env:
      LOG_LEVEL: 'debug'
